---
title: "DRG Cleaning"

author: "Carlos Resurreccion"

date: "2024-07-01"

---

In [106]:
system("git submodule update --init --recursive")
# system("git submodule foreach --recursive git fetch && git submodule foreach --recursive && git reset --hard origin/main")
# Sys.setenv(PYTHONPATH = here::here("data-cleaning", "grouper"))

In [107]:
# Delete all R objects and run garbage collection so we start with a clean slate
rm(list = ls())
gc()

       used    (Mb)  gc trigger (Mb)  max used (Mb)
Ncells 2574311 137.5  5040384   269.2  5040384 269.2
Vcells 4817537  36.8 21596529   164.8 20387082 155.6

In [108]:
# Load libraries and minor parameters
source(here::here("data-cleaning/r_scripts", "00_libraries-params.R"))

## Primary Parameters

In [109]:
# Prompt Options:
to_prompt <- FALSE # Whether to prompt for user inputs or not (if FALSE, default values in this cell will be used)
thai_prompt <- TRUE # Whether to prompt for thai grouper even if bypassing all other prompts

# IMPORTANT PARAMETERS:
full_claims_prefix <- "claims_extract_CLAIMS " # Include spaces if there are any
# Assign the correct file extension based on the year
# Read the contents of year_to_load.txt as a string
year_to_load <- fread(here::here("data-cleaning", "cache", "year_to_load.txt"), header = FALSE, colClasses = "character")[[1]]
print(year_to_load)
file_type <- if (year_to_load %in% c(2022:2023)) ".tsv" else ".csv"
print(file_type)
gcs_email <- "271591364028-compute@developer.gserviceaccount.com" # Service Account to use
gcp_proj <- system("gcloud config get-value project", intern = TRUE) # get current GCP Project
gcs_bucket <- "phic-claims-checkpoints" # Name of GCS bucket
gcs_pre_fpath <- "pre-tdrg" # Name of folder path prefix in GCS bucket for thai grouper input
gcs_post_fpath <- "post-tdrg" # Name of folder path prefix in GCS bucket for thai grouper output
gcs_spc_fpath <- "spc"
bq_dataset <- "phic" # bq dataset
bq_table <- paste0("temp_claims_", year_to_load) # temp bq table, later renamed to claims_20XX1231 in Push to BQ section

# Input:
to_sample <- TRUE # Whether to sample each split_part by sample_size_divisor (useful when iterating through code runs in quick succession)
sample_size_divisor <- 625 # Sample size divisor: Formula for sample size is total_rows / split_parts / sample_size_divisor. Choose between 5, 25, 125, and 625

# Output:
to_write <- TRUE # Whether to write out checkpoint_1 files (everything up until converting for grouper export)
to_combine <- TRUE # Whether to combine checkpoint 1 files into one data.table
to_group <- TRUE # Whether to export for the batch grouper or not
to_gcs <- TRUE # Whether to push to GCS or nt (Thai Grouper Input/Output)
to_bq <- TRUE # Whether to push to BQ or not
to_drop_bq <- TRUE # Whether to overwrite the existing BQ table

# Columns to drop
drop_cols <- c( # Which columns to drop
  paste0("ICDCODE", 13:14), # Start
  "ICCODED15", # note that ICDCODE15 is misspelled as ICCODED15 in all claims
  paste0("ICDCODE", 16:170) # Continuation
)

drop_cols_manual <- c(
  "MEMCAT_SUBCHILD_DESC" # Drop as per Cel's suggestion
)

# Flush files
to_flush_master <- FALSE # whether to flush aux-files, checkpoints, profvis, debug, cache, and samples
to_flush_partial <- FALSE # whether to flush partial files (raw files but split into split_parts parts)

# Control random behavior for reproducibility
global_seed <- seed <- 123 # Choose a number as seed
set.seed(seed) # Setting the seed reproducibility (Important for stuff like randomly choosing a pdx among multiple possible options)

# Machine Specifications
ram_size <- 64 # Input virtual or physical machine's RAM size here

# Print GCP project
message(paste("GCP Project:", gcp_proj, "\n"))

[1] "2022"
[1] ".tsv"

GCP Project: drg-pipeline

In [110]:
# other parameters for manual adjustments
manual_patterns_to_replace <- c("\\b0800\\b", "\\b080\\b", "\\b0809\\b") # ICD codes to replace
manual_code_replacements <- c("O800", "O80", "O809") # ICD code replacements

## Secondary (Debug) Parameters

In [111]:
# Debug Parameters:
to_debug <- FALSE # whether to print debug statements
to_profvis <- FALSE # Conduct runtime duration analysis via profvis or not
to_view_checks <- TRUE # Whether to view checks and print statements
to_view_checks_parallel <- FALSE # Whether to view intermediate per split_part/chunk checks and print statements (not consolidated) when parallelized
to_parallel <- TRUE # Whether to parallelize each split_parts split_part into availableCores() chunks. Cuts down processing time from 120min to 15min.
to_split_read <- FALSE # WARNING: TRUE uses a lot of memory!!
to_dec_mem_usage <- TRUE # Whether to run rm() and gc() at every possible step
tmp_nrow <- Inf # Per split_part/chunk end_nrow (leave at Inf)
diff_chars <- 0
split_parts <- 15 # How many (integer) parts to split the 12+m row claims file into
end_nrow <- 10 # How many rows/entries to show in summary tables
max_bq_rows <- 15000 # Max rows to return for bq query
encode <- "unknown" # Choices: unknown, UTF-8, Latin-1
# sep <- "," # Choices: "," or "\t"
is_unix <- if (.Platform$OS.type == "unix") TRUE else FALSE # Detect operating system architecture

ram_buffer <- 0.1 # How much of a RAM buffer to leave for the OS

## File Paths

In [112]:
# Folder Path Prefixes:
clean_prefix <- "data-cleaning"
data_prefix <- file.path(clean_prefix, "data")
claims_prefix <- file.path(data_prefix, "claims")
checkpoint_1_prefix <- "checkpoint_1_claims_"
checkpoint_2_prefix <- "checkpoint_2_claims_"
checkpoint_3_prefix <- "DRG_Grouped_"
checkpoint_4_prefix <- "checkpoint_4_thai_grouper_input_"
checkpoint_5_prefix <- toupper(paste0(gcs_pre_fpath, "_", checkpoint_4_prefix))
checkpoint_6_prefix <- "checkpoint_6_grouped_claims"
checkpoint_7a_prefix <- "python_input_1"
checkpoint_7b_prefix <- "python_input_2"
checkpoint_10_prefix <- "stata"

# Folder Paths:
chkpt_path <- file.path(data_prefix, "checkpoints")
checkpoint_1_path <- file.path(chkpt_path, "checkpoint_1_partial_clean_claims")
checkpoint_2_path <- file.path(chkpt_path, "checkpoint_2_master_clean_claims")
checkpoint_3_path <- file.path(chkpt_path, "checkpoint_3_thai_partial_input")
checkpoint_4_path <- file.path(chkpt_path, "checkpoint_4_thai_master_input")
checkpoint_5_path <- file.path(chkpt_path, "checkpoint_5_thai_output")
checkpoint_6_path <- file.path(chkpt_path, "checkpoint_6_thai_merged")
checkpoint_7_path <- file.path(chkpt_path, "checkpoint_7_py_input")
checkpoint_8_path <- file.path(chkpt_path, "checkpoint_8_py_output")
checkpoint_9_path <- file.path(chkpt_path, "checkpoint_9_grouper_differences")
checkpoint_10_path <- file.path(chkpt_path, "checkpoint_10_stata")
cache_path <- file.path(clean_prefix, "cache")
aux_path <- file.path(data_prefix, "aux-files")
raw_claims_path <- file.path(claims_prefix, "raw")
raw_claims_parts_path <- file.path(claims_prefix, "raw", "parts")
raw_claims_samples_path <- file.path(claims_prefix, "raw", "samples")
profvis_path <- file.path(data_prefix, "profvis")
debug_path <- file.path("data-cleaning", "debug")

# File Paths
profvis_fpath <- here("data-cleaning", "data", "profvis", "profvis.html")

# Create directories:
created_dirs <- c() # Initialize empty vector
# For all "_path" variables, create a directory with that path
# Excludes "_fpath" variables
for (path in mget(ls(pattern = "_path$"), envir = .GlobalEnv)) {
  full_path <- here(path)
  if (!dir.exists(full_path)) {
    dir.create(full_path, recursive = TRUE)
    created_dirs <- c(created_dirs, full_path)
  }
}

# Print directories created if any
if (length(created_dirs) == 0) {
  message("All directories exist.\n")
} else {
  message("The following directories were created:\n")
  message(paste(paste(created_dirs, collapse = ",\n"), "\n"))
}

# Commonly Used File Paths:
full_claims_file <- here(
  raw_claims_path,
  paste0(full_claims_prefix, year_to_load, file_type) # Use the file_type variable here
)

All directories exist.

## Parameter Validation Logic

Checking if parameters are valid, especially for the current machine type (e.g. RAM size)

Additionally, ask for parameters if to_bypass_prompts is false

In [113]:
# Stop if forecasted memory usage is expected to crash the system
if (!split_parts == as.integer(split_parts) || split_parts <= 1) stop("ERROR: split_parts must be an integer greater than or equal to 2!")
if (ram_size <= 64 && split_parts <= 2) stop("Please set split_parts to at least 3 for 64 GB machines or it will likely crash")
if (ram_size <= 32 && split_parts <= 4) stop("Please set split_parts to at least 5 for 32 GB machines or it will likely crash")
if (ram_size <= 32 && to_split_read == TRUE) stop("Please set to_split_read to TRUE for 32 GB machines or it will likely crash")

# Function to prompt for input with default value
prompt_with_default <- function(prompt_text, default_value) {
  if (to_prompt) {
    user_input <- readline(prompt = paste0(prompt_text, " [Default: ", default_value, "]: "))
    if (user_input == "") {
      return(default_value)
    } else {
      return(user_input)
    }
  } else {
    message(
      paste0(
        "Using default value (",
        default_value, ") for ",
        deparse(substitute(default_value))
      )
    )
    return(default_value)
  }
}

# Set parameters based on prompts or defaults
full_claims_prefix <- prompt_with_default("Enter full_claims_prefix", full_claims_prefix)
full_claims_bq_prefix <- str_replace_all(full_claims_prefix, " ", "\\\\ ")
year_to_load <- prompt_with_default("Enter year_to_load", year_to_load)

# Prompt for whether to sample
to_sample <- as.logical(prompt_with_default("Sample data? (TRUE/FALSE)", to_sample))
sample_size_divisor <- as.integer(prompt_with_default("Enter sample_size_divisor", sample_size_divisor))

# Prompt for output options
to_write <- as.logical(prompt_with_default("Write output files? (TRUE/FALSE)", to_write))
to_combine <- as.logical(prompt_with_default("Combine files? (TRUE/FALSE)", to_combine))
to_group <- as.logical(prompt_with_default("Export for batch grouper? (TRUE/FALSE)", to_group))

# Flush options
to_flush_master <- as.logical(prompt_with_default("Flush master files? (TRUE/FALSE)", to_flush_master))
to_flush_partial <- as.logical(prompt_with_default("Flush partial files? (TRUE/FALSE)", to_flush_partial))

# RAM settings
ram_size <- as.numeric(prompt_with_default("Enter RAM size (GB)", ram_size))
# ram_buffer <- as.numeric(prompt_with_default("Enter RAM buffer (0.0-1.0)", ram_buffer))
ram_limit <- (1 - ram_buffer) * ram_size * (1024^3)

# Allowing each future_lapply session to use more memory
options(future.globals.maxSize = ram_limit)

# Compute the RAM limit for R processes, leaving the buffer for the OS
ram_limit_gb <- round((1 - ram_buffer) * ram_size, 0)

# Print the set RAM limit
message(sprintf("Setting future.globals.maxSize to: %.1f GB", ram_limit / (1024^3)))

Using default value (claims_extract_CLAIMS ) for full_claims_prefix

Using default value (2022) for year_to_load

Using default value (TRUE) for to_sample

Using default value (625) for sample_size_divisor

Using default value (TRUE) for to_write

Using default value (TRUE) for to_combine

Using default value (TRUE) for to_group

Using default value (FALSE) for to_flush_master

Using default value (FALSE) for to_flush_partial

Using default value (64) for ram_size

Setting future.globals.maxSize to: 57.6 GB

## Loading

### Load Required Libraries & Initial Functions

In [114]:
# Hide verbose outputs and warnings
options(verbose = FALSE) # Hide verbose output for script and library loading
options(warn = -1) # Hide warnings for script sourcing and library loading

In [115]:
scripts <- list( # List of scripts to source
  # lib_params = "00_libraries-params.R",
  cleaning = "01_cleaning-functions.R",
  clinical = "02_clinical-functions.R",
  timing_debug = "03_timing-debug-functions.R",
  summary = "04_summary-functions.R",
  io = "05_io-functions.R"
)

# Loop to source above scripts
for (script in scripts) source(here("data-cleaning/r_scripts", script))

In [116]:
# since verbose = TRUE is way too verbose compared to default
options(warn = 1) # Reenable warnings; see above comments

### Load Full Claims from GCS

In [117]:
# Load raw claims from GCS only if they don't exist on the VM yet
for (year in 2018:2023) {
  # Assign the correct file extension based on the year
  file_type <- if (year %in% c(2022:2023)) ".tsv" else ".csv"
  file_name <- paste0(full_claims_prefix, year, file_type)
  bq_name <- paste0(full_claims_bq_prefix, year, file_type)

  # Check if the file exists in the target directory
  file_path <- here(raw_claims_path, file_name)
  exists <- file.exists(file_path)

  # If the file does not exist, run the gsutil cp command
  if (!exists) {
    if (!is.null(gcp_proj) && gcp_proj == "drg-pipeline") {
      system(paste0("cd .. && gsutil cp gs://phic-claims-raw/", bq_name, " ", raw_claims_path),
        intern = FALSE, ignore.stderr = FALSE
      )
    } else {
      stop("Error: GCP Project is not null and is not drg-pipeline")
    }
  } else {
    message(paste("File", file_name, "already exists in the target directory. Skipping download.\n"))
  }
}

File claims_extract_CLAIMS 2018.csv already exists in the target directory. Skipping download.


File claims_extract_CLAIMS 2019.csv already exists in the target directory. Skipping download.


File claims_extract_CLAIMS 2020.csv already exists in the target directory. Skipping download.


File claims_extract_CLAIMS 2021.csv already exists in the target directory. Skipping download.


File claims_extract_CLAIMS 2022.tsv already exists in the target directory. Skipping download.


File claims_extract_CLAIMS 2023.tsv already exists in the target directory. Skipping download.

### Load Mapping Data

#### Define Query Function for BigQuery

In [118]:
# Function to query BigQuery and optionally cache the results as a CSV
query_bq_to_dt <- function(query, file_path, cache, max_bq_rows) {
  if (file.exists(file_path)) {
    message(paste(basename(file_path), "already exists, loading from CSV"))
    dt <- fread(file_path)
  } else {
    message(paste("Querying BigQuery for", basename(file_path)))
    dt <- as.data.table(bq_table_download(
      bq_project_query(gcp_proj, query),
      n_max = max_bq_rows
    ))
    if (cache) {
      fwrite(dt, file_path)
    }
  }
  # return bq table as dt
  return(dt)
}

#### BigQuery Proper

In [119]:
# 1. Query and load `grouper_v5.proc`
proc_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".grouper_v5.proc` LIMIT ", max_bq_rows
)
proc <- query_bq_to_dt(proc_query, here(aux_path, "proc.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)
proc[, CODE := as.character(CODE)]

# 2. Query and load `phic.acr_rvs_map`
rvs_icd9_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".phic.acr_rvs_map` LIMIT ", max_bq_rows
)
rvs_icd9 <- query_bq_to_dt(rvs_icd9_query, here(aux_path, "rvs_icd9cm.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)

# Convert rvs to character and handle icd9cm conversion carefully
rvs_icd9 <- rvs_icd9[, .(
  rvs = as.character(rvs),
  icd9cm = as.character(as.numeric(icd9cm) * 100)
)]

# Merge with proc to classify by DRGUSE
rvs_icd9 <- merge(rvs_icd9, proc[, .(CODE, DRGUSE)],
  by.x = "icd9cm", by.y = "CODE", all.x = TRUE
)

# Remove DRGUSE and filter out NAs
rvs_icd9 <- rvs_icd9[, is_drg := !is.na(DRGUSE) &
  DRGUSE][!is.na(rvs) & !is.na(icd9cm), -"DRGUSE"]

# 3. Query and load `phic.acr_procedure`
acr_rvs_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".phic.acr_procedure` LIMIT ", max_bq_rows
)
acr_rvs <- query_bq_to_dt(acr_rvs_query, here(aux_path, "acr_rvs.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)

# 4. Query and load `grouper_v5.i10`
i10_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".grouper_v5.i10` LIMIT ", max_bq_rows
)
tdrg_icd10 <- query_bq_to_dt(i10_query, here(aux_path, "i10.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)
setkey(tdrg_icd10, "CODE")

# Subset and assign to acc_pdx
acc_pdx <- unique(tdrg_icd10[ACCPDX == "Y", CODE])

# 5. Query and load `icd.phl_icd10`
phl_icd10_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".icd.phl_icd10` LIMIT ", max_bq_rows
)
phl_icd10 <- query_bq_to_dt(phl_icd10_query, here(aux_path, "phl_icd10.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)

# Filter and process neoplasms
neoplasms_dt_actual <- as.data.table(phl_icd10[
  grepl("/", icd10),
  .(icd10)
][, icd10 := sapply(strsplit(icd10, ","), function(x) trimws(x[2]))])

# 6. Query and load `drg-pipeline.grouper_v5.i10vx`
i10vx_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".grouper_v5.i10vx` LIMIT ", max_bq_rows
)
i10vx <- query_bq_to_dt(i10vx_query, here(aux_path, "i10vx.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)
setkey(i10vx, "code")
acc_icd <- unique(i10vx[, code])

# 7. Query and load `drg-pipeline.hci.temp_hci`
hci_query <- paste0(
  "SELECT * FROM `", gcp_proj,
  ".hci.temp_hci` LIMIT ", max_bq_rows
)
hci <- query_bq_to_dt(hci_query, here(aux_path, "hci.csv"),
  cache = FALSE, max_bq_rows = max_bq_rows
)

Querying BigQuery for proc.csv

Querying BigQuery for rvs_icd9cm.csv

Querying BigQuery for acr_rvs.csv

Querying BigQuery for i10.csv

Querying BigQuery for phl_icd10.csv

Querying BigQuery for i10vx.csv

Querying BigQuery for hci.csv

In [120]:
# cat(unique(hci$PMCC_NO), sep = "\n")
# cat(unique(hci$CAT_24), sep = "\n")

In [121]:
# Print the column names enclosed in quotes and separated by newlines
# colnames_list <- colnames(fread(full_claims_file, nrows = 1))
# cat(paste0('"', colnames_list, '"', collapse = "\n"))

# str(fread(full_claims_file, nrows = 10000, colClasses = "character"))

### Loading Cached Objects

Total Rows File, sample size computation, suffix definition

In [122]:
# Load cached total rows file if available, saves ~10 seconds of runtime
total_rows_file <- here(cache_path, paste0("total_rows_", year_to_load, ".rds"))
if (file.exists(total_rows_file)) {
  total_rows <- readRDS(total_rows_file)
  message(paste("Total Rows via cached object:", total_rows))
} else {
  total_rows <- fread(file = full_claims_file, select = 1L, header = TRUE, colClasses = "character")[, .N]
  saveRDS(total_rows, file = total_rows_file)
  message(paste("Total Rows via fread:", total_rows))
}

# Compute sample size when splitting and when not,
# only relevant when sampling
if (to_split) {
  sample_size <- ceiling(total_rows / split_parts / sample_size_divisor)
} else {
  sample_size <- ceiling(total_rows / sample_size_divisor)
}

# suffix appended to files to indicate if they are from sampled or full runs
suffix <- paste0(
  ifelse(to_sample, paste0("_sampled_", sample_size, "_"), "_full_")
)

Total Rows via cached object: 12757064

## Function Definitions

### Functions called in Process Chunk

Define Clean Data Function

In [123]:
# Define main clean data function, which does majority of the data cleaning on the claims file
clean_data <- function(dt) {
  # Rename columns based on column_mappings
  available_columns <- colnames(dt)

  # Convert source year to integer
  if ("ADMISSION_YEAR" %in% available_columns) {
    # do nothing
  } else {
    dt[, SRC_YR := as.integer(year_to_load)]
  }

  dt[, is_covid := FALSE]

  # Identify the columns to rename based on the mapping
  old_names <- available_columns[available_columns %in% names(column_mappings)]
  new_names <- sapply(old_names, function(col) column_mappings[[col]])

  # Rename the columns in the data.table
  setnames(dt, old = old_names, new = new_names)

  # Check if renaming was successful
  rename_success <- all(new_names %in% available_columns)

  dt[, c1 := clin_c1]
  dt[, c2 := clin_c2]

  # Convert time_adm and time_dis for 2022-2023 format

  # Strip fractional seconds and handle AM/PM conversion properly using as.POSIXct()
  dt[, time_adm := ifelse(grepl("AM|PM", time_adm),
    format(as.POSIXct(sub("\\.\\d+ ", " ", time_adm), format = "%m/%d/%Y %I:%M:%S %p"), "%H:%M"),
    time_adm
  )]

  dt[, time_dis := ifelse(grepl("AM|PM", time_dis),
    format(as.POSIXct(sub("\\.\\d+ ", " ", time_dis), format = "%m/%d/%Y %I:%M:%S %p"), "%H:%M"),
    time_dis
  )]

  # Collapse and clean ICD and RVS columns
  dt <- collapse_and_clean_icd_rvs(dt)

  # # Helper function to clean and compare clinical columns
  # clean_clinical_column <- function(col_name) {
  #   dt[, (paste0(col_name, "_orig")) := dt[[col_name]]]
  #   dt[, (col_name) := clean_column(
  #     dt[[col_name]], na_like_strings, neoplasms_dt_actual
  #   )]
  #   dt[, (paste0(col_name, "_orig")) := sapply(
  #     get(paste0(col_name, "_orig")), toString
  #   )]
  #   dt[, (col_name) := sapply(get(col_name), toString)]

  #   # Compare cleaning results
  #   dt[
  #     !is.na(get(paste0(col_name, "_orig"))) & get(col_name) !=
  #       get(paste0(col_name, "_orig")),
  #     .(
  #       old_code = get(paste0(col_name, "_orig")),
  #       new_code = get(col_name), count = .N
  #     ),
  #     by = .(get(paste0(col_name, "_orig")), get(col_name))
  #   ]
  # }

  # Helper function to clean and compare clinical columns
  clean_clinical_column <- function(col_name) {
    # Store the original column
    dt[, (paste0(col_name, "_orig")) := dt[[col_name]]]

    # Apply the clean_column function, which now returns a list of cleaned_col and is_covid
    cleaned_data <- clean_column(dt[[col_name]], na_like_strings, neoplasms_dt_actual)

    # Extract cleaned column and is_covid flag
    cleaned_col <- cleaned_data$cleaned_col
    is_covid_flag <- cleaned_data$is_covid

    # Update the cleaned column
    dt[, (col_name) := cleaned_col]

    # Store the original column as a string (for comparison purposes)
    dt[, (paste0(col_name, "_orig")) := sapply(get(paste0(col_name, "_orig")), toString)]

    # Convert the cleaned column to a string for comparison
    dt[, (col_name) := sapply(get(col_name), toString)]

    # Update is_covid column if needed
    # If is_covid is FALSE in dt, but the new is_covid_flag is TRUE, set is_covid to TRUE
    dt[, is_covid := ifelse(is_covid == FALSE & is_covid_flag == TRUE, TRUE, is_covid)]

    # Compare cleaning results (only rows where the cleaned column differs from the original)
    comparison <- dt[
      !is.na(get(paste0(col_name, "_orig"))) & get(col_name) != get(paste0(col_name, "_orig")),
      .(
        old_code = get(paste0(col_name, "_orig")),
        new_code = get(col_name), count = .N
      ),
      by = .(get(paste0(col_name, "_orig")), get(col_name))
    ]

    return(comparison)
  }

  # Clean and compare c1 and c2 columns
  c1_cleaning_comparison <- clean_clinical_column("c1")
  c2_cleaning_comparison <- clean_clinical_column("c2")

  # Function to replace multiple patterns with corresponding replacements
  replace_multiple_patterns <- function(text, patterns, replacements) {
    # Ensure patterns and replacements are the same length
    if (length(patterns) != length(replacements)) {
      stop("Patterns and replacements must have the same length.")
    }

    # Perform replacements
    modified_text <- stri_replace_all_regex(
      text,
      pattern = patterns,
      replacement = replacements,
      vectorize_all = FALSE # Apply all replacements simultaneously
    )

    # return the text after modification
    return(modified_text)
  }

  # Apply multi-replacement function to implement manual replacements
  dt[, clin_icd := lapply(clin_icd,
    replace_multiple_patterns,
    patterns = manual_patterns_to_replace,
    replacements = manual_code_replacements
  )]
  dt[, c1 := lapply(c1,
    replace_multiple_patterns,
    patterns = manual_patterns_to_replace,
    replacements = manual_code_replacements
  )]
  dt[, c2 := lapply(c2,
    replace_multiple_patterns,
    patterns = manual_patterns_to_replace,
    replacements = manual_code_replacements
  )]

  # Handle any lumped ICD codes by splitting them
  dt[, c1 := remove_lumped_icd_codes(c1)]
  # Handle any lumped ICD codes by splitting them
  dt[, c2 := remove_lumped_icd_codes(c2)]
  # Convert the cleaned columns into vectors
  dt[, c1 := split_to_vector(c1)]
  # Convert the cleaned columns into vectors
  dt[, c2 := split_to_vector(c2)]

  # # Remove lumped ICD codes
  # dt[, c1 := remove_lumped_icd_codes(c1)]
  # dt[, c2 := remove_lumped_icd_codes(c2)]
  # dt[, clin_rvs := remove_lumped_rvs_codes(clin_rvs)]

  # Clean clinical columns
  clean_clin_col_res <- clean_clinical_columns(dt)
  dt <- clean_clin_col_res$dt

  # Replace empty strings with NA and remap patient data
  replace_result <- replace_empty_with_na(dt = dt, to_view_checks)
  dt <- replace_result$return_data
  empty_strings_replaced_1 <- replace_result$return_replacement_summary

  remapping_results <- remap_patient_data(dt, to_view_checks)
  dt <- remapping_results$data
  return_summary_list <- list(
    rename_success = rename_success,
    ICD_replacements_1 = c1_cleaning_comparison,
    ICD_replacements_2 = c2_cleaning_comparison,
    pat_type_mapped = remapping_results$pat_type_mapped,
    pat_memcat_parent_mapped = remapping_results$pat_memcat_parent_mapped,
    pat_memcat_child_mapped = remapping_results$pat_memcat_child_mapped,
    clin_discharge_mapped = remapping_results$clin_discharge_mapped,
    claim_status_mapped = remapping_results$claim_status_mapped,
    pat_type_unmapped = remapping_results$pat_type_unmapped,
    memcat_parent_unmapped = remapping_results$memcat_parent_unmapped,
    memcat_child_unmapped = remapping_results$memcat_child_unmapped,
    discharge_unmapped = remapping_results$discharge_unmapped,
    claim_status_unmapped = remapping_results$claim_status_unmapped,
    discard_rvs_one = clean_clin_col_res$discard_rvs_one,
    discard_rvs_two = clean_clin_col_res$discard_rvs_two,
    empty_strings_replaced_1 = empty_strings_replaced_1
  )

  return(
    list(
      # data to return for further processing
      return_data = dt,
      # summary to return for checks and output
      return_summary = return_summary_list
    )
  )
}

Define RVS Mapping Function

In [124]:
# Define function to map RVS codes to ICD9 codes
map_rvs_icd9 <- function(clin_rvs, rvs_icd9) {
  split_codes <- split_rvs_codes(rvs_icd9)
  rvs_maps <- create_rvs_map_lists(split_codes$with_drg)

  rvs_map_solo_env <- as.environment(rvs_maps$rvs_map_solo)

  return(
    list(
      # main return variable (a column) to save back to dt
      icd9_list = get_icd9_codes(clin_rvs, rvs_map_solo_env),
      # other return variables that are for checks and outputs
      rvs_map_list = rvs_maps$rvs_map_list,
      rvss = unique(unlist(clin_rvs)),
      mappable_rvs = intersect(unique(unlist(clin_rvs)), rvs_icd9$rvs),
      unmappable_rvs = setdiff(unique(unlist(clin_rvs)), rvs_icd9$rvs),
      multi_mapped_rvs = intersect(unique(unlist(clin_rvs)), names(rvs_maps$rvs_map_list)),
      without_drg = unique(rvs_icd9[!rvs %in% names(rvs_maps$rvs_map_list)]$rvs)
    )
  )
}

Define ICD10 Application Function

In [125]:
implement_icd10_mapping <- function(c1, c2, clin_icd, tdrg_icd10) {
  # Step 1: Get all unique ICD codes from the provided columns (c1, c2, and clin_icd)
  icds <- get_unique_icd_codes(c1, c2, clin_icd)

  # Step 2: Create an environment for Thai ICD10 codes for faster lookup
  # This uses the unique set of ICD10 codes in the tdrg_icd10 table.
  thai_icd10_env <- create_thai_icd10_environment(
    unique(tdrg_icd10$CODE)
  )

  # Step 3: Create a second environment for Thai ICD10 neoplasm codes (those with slashes '/')
  neoplasms_env <- create_thai_icd10_environment(
    unique(tdrg_icd10[grepl("/", tdrg_icd10$CODE), "CODE"])
  )

  # Step 4: Find direct matches between the provided ICD codes (icds) and the Thai ICD10 environment
  direct_match_codes <- find_direct_icd_matches(
    icds, thai_icd10_env
  )

  # Step 5: Generate the full ICD10 mapping for the ICD codes,
  # considering both Thai ICD10 environment and neoplasms environment.
  icd_mapping_info <- generate_icd10_mapping(
    icds, thai_icd10_env, neoplasms_env
  )
  # Extract the mapping and the count of modified mappings
  icd_mapping <- icd_mapping_info$icd_mapping
  modified_count <- icd_mapping_info$modified_count

  # Step 6: Identify ICD codes that were not successfully mapped.
  unmatched_icds <- setdiff(icds, names(icd_mapping))

  # Step 7: If there are unmatched ICD codes, gather their source information (c1, c2, clin_icd)
  # and the count of occurrences in each column.
  if (length(unmatched_icds) > 0) {
    unmatched_sources <- data.table(
      code = unmatched_icds, source = NA_character_, count = 0
    )
    # Loop over the columns (c1, c2, clin_icd) to fill in source and count details for unmatched codes.
    for (col_name in c("c1", "c2", "clin_icd")) {
      col_values <- get(col_name)
      unmatched_sources[
        code %in% unlist(col_values),
        source := col_name
      ]
      unmatched_sources[
        code %in% unlist(col_values),
        count := count + table(unlist(col_values))[code]
      ]
    }
    # Order unmatched codes by their occurrence count in descending order
    unmatched_sources <- unmatched_sources[order(-count)]
  } else {
    # If there are no unmatched codes, return an empty data.table.
    unmatched_sources <- data.table()
  }

  # Step 8: Create a data.table containing the mapping between PHL (input) ICD10 codes
  # and Thai DRG ICD10 codes.
  icd10_map <- data.table(
    phl_icd10 = names(icd_mapping),
    tdrg_icd10 = unlist(icd_mapping)
  )

  # Step 9: If debugging is enabled, save the mapping to a CSV file in the cache directory.
  if (to_debug) {
    fwrite(icd10_map, paste0("cache/icd10_map_file_", year_to_load, ".csv"))
  }

  # Step 10: Create an environment from the ICD10 mapping for fast lookup during column mapping.
  icd10_env <- list2env(
    setNames(as.list(icd10_map$tdrg_icd10), icd10_map$phl_icd10)
  )

  # Step 11: Apply the ICD10 mapping to the columns c1, c2, and clin_icd
  # This updates these columns based on the generated ICD10 environment.
  mapped_columns <- apply_icd10_mapping_to_columns(
    c1, c2, clin_icd, icd10_env
  )

  # Step 12: Return a list containing the mapped columns and other information for further checks and outputs:
  # - The updated columns (c1, c2, clin_icd)
  # - The full ICD10 map (icd10_map_dt)
  # - The unique ICD codes
  # - Direct matches found
  # - Unmatched ICDs and their source information
  return(
    list(
      c1 = mapped_columns$c1,
      c2 = mapped_columns$c2,
      clin_icd = mapped_columns$clin_icd,
      icd10_map_dt = icd10_map,
      unique_icds = icds,
      direct_matches = direct_match_codes,
      unmatched = unmatched_icds,
      unmatched_sources = unmatched_sources
    )
  )
}

### Functions called in Main Logic Function

Define Process Chunk

In [126]:
##################################################################################################################################
################################################### START OF PROCESS CHUNK #######################################################
##################################################################################################################################

# Define process_chunk (not to be confused with process_part) that processes each part in nthreads chunks
process_chunk <- function(chunk, to_view_checks, rvs_icd9, tdrg_icd10, acc_pdx) {
  # Step 1: Set up environment for viewing or suppressing output
  # If 'to_view_checks' is TRUE, you can enable message viewing (commented out here).
  # Otherwise, sink (redirect output) to a temporary file to suppress output.
  if (to_view_checks) {
    # message("\rViewing checks")
  } else {
    sink(tempfile())
    on.exit(sink(), add = TRUE)
  }

  # Step 2: Clean the data in the 'chunk'
  clean_result <- clean_data(chunk)
  chunk <- clean_result$return_data # Update chunk with cleaned data
  if (to_debug) print("checkpoint 1") # Debug checkpoint
  if (to_debug) print(unique(chunk$c1)) # Print unique values in 'c1' for debugging

  # Step 3: Optionally save intermediate result to a file (debugging)
  if (to_debug) fwrite(chunk, "test1.csv")

  # Step 4: Map clinical RVS (Relative Value Scale) codes to ICD9 using 'rvs_icd9'
  rvs_mapping_result <- map_rvs_icd9(chunk$clin_rvs, rvs_icd9)
  # Store the mapped ICD9 list into the chunk
  chunk[, icd9_list := rvs_mapping_result$icd9_list]

  # Step 5: Optionally save another intermediate result to a file (debugging)
  if (to_debug) fwrite(chunk, "test2.csv")

  # Step 6: Extract columns c1, c2, and clin_icd for ICD10 mapping
  c1 <- chunk$c1
  c2 <- chunk$c2
  clin_icd <- chunk$clin_icd
  if (to_debug) print("checkpoint 2") # Debug checkpoint
  if (to_debug) print(unique(c1)) # Print unique values in 'c1' for debugging

  # Step 7: Perform ICD10 mapping using the extracted columns and 'tdrg_icd10' mapping data
  icd10_mapping_result <- implement_icd10_mapping(
    c1, c2, clin_icd, tdrg_icd10
  )
  # Update chunk with the mapped ICD10 codes
  chunk[, c1 := icd10_mapping_result$c1]
  chunk[, c2 := icd10_mapping_result$c2]
  chunk[, clin_icd := icd10_mapping_result$clin_icd]

  # Step 8: Replace any empty strings with NA values, returning a summary of replacements
  res2 <- replace_empty_with_na(dt = chunk, to_view_checks)
  chunk <- res2$return_data # Update chunk with cleaned data
  empty_strings_replaced_2 <- res2$return_replacement_summary # Store replacement summary

  if (to_debug) print("checkpoint 3") # Debug checkpoint
  if (to_debug) print(unique(chunk$c1)) # Print unique values in 'c1' for debugging

  # Step 9: Define a function to remove all whitespace from character vectors
  remove_whitespace <- function(x) {
    if (is.null(x) || length(x) == 0) {
      return(NA_character_) # Return NA for NULL or empty lists
    } else {
      return(gsub("\\s+", "", x)) # Remove all whitespace characters
    }
  }

  # Step 10: Apply the remove_whitespace function to the list columns 'c1', 'c2', and 'clin_icd'
  chunk[, c1 := lapply(c1, remove_whitespace)]
  chunk[, c2 := lapply(c2, remove_whitespace)]
  chunk[, clin_icd := lapply(clin_icd, remove_whitespace)]

  if (to_debug) print("checkpoint 4") # Debug checkpoint
  if (to_debug) print(unique(chunk$c1)) # Print unique values in 'c1' for debugging

  # Step 11: Optionally save a CSV file containing the column names and their types (for debugging)
  if (to_debug) fwrite(data.table(Column = colnames(chunk), Class = sapply(chunk, class)), "class.csv")

  # Step 12: Apply a function to find the primary diagnosis (pdx) based on 'c1', 'c2', and 'clin_icd'
  pdx_result <- apply_find_pdx(
    chunk$c1, chunk$c2, chunk$clin_icd, acc_pdx
  )
  # Store the primary diagnosis (pdx) and its code into the chunk
  chunk$pdx <- pdx_result$pdx
  chunk$pdx_code <- pdx_result$pdx_code

  # Step 13: Optionally save another intermediate result to a file (debugging)
  if (to_debug) fwrite(chunk, "test2c.csv")
  if (to_debug) print("checkpoint 5") # Debug checkpoint
  if (to_debug) print(unique(chunk$c1)) # Print unique values in 'c1' for debugging

  # Step 14: Define a function to remove the primary diagnosis (pdx) from list columns (c1, c2, clin_icd)
  remove_pdx_from_list <- function(pdx, lst) {
    if (!is.na(pdx)) {
      # Remove the primary diagnosis from the list
      lst <- setdiff(lst, pdx)
    }
    return(lst)
  }

  # Step 15: Apply the 'remove_pdx_from_list' function to each row of 'c1', 'c2', and 'clin_icd'
  chunk[, c1 := lapply(seq_len(.N), function(i) as.character(remove_pdx_from_list(pdx[i], c1[[i]])))]
  chunk[, c2 := lapply(seq_len(.N), function(i) as.character(remove_pdx_from_list(pdx[i], c2[[i]])))]
  chunk[, clin_icd := lapply(seq_len(.N), function(i) as.character(remove_pdx_from_list(pdx[i], clin_icd[[i]])))]

  if (to_debug) print("checkpoint 6") # Debug checkpoint
  if (to_debug) print(unique(chunk$c1)) # Print unique values in 'c1' for debugging

  # Step 16: Create a summary by combining clean results and ICD10 mapping information
  chunk_summary <- modifyList(
    clean_result$return_summary,
    list(
      unique_icds = icd10_mapping_result$unique_icds,
      direct_matches = icd10_mapping_result$direct_matches,
      unmatched = icd10_mapping_result$unmatched,
      unmatched_sources = icd10_mapping_result$unmatched_sources,
      icd10_map_dt = icd10_mapping_result$icd10_map_dt,
      rvss = rvs_mapping_result$rvss,
      mappable_rvs = rvs_mapping_result$mappable_rvs,
      unmappable_rvs = rvs_mapping_result$unmappable_rvs,
      multi_mapped_rvs = rvs_mapping_result$multi_mapped_rvs,
      without_drg = rvs_mapping_result$without_drg
    )
  )

  # Step 17: Optionally trigger garbage collection to reduce memory usage
  if (to_dec_mem_usage) gc() # Trigger garbage collection if needed

  # Step 18: Return the processed chunk and summary information
  return(
    list(
      return_chunk = chunk, # Return the processed chunk data
      return_summary = chunk_summary # Return the summary for checks and outputs
    )
  )
}

##################################################################################################################################
#################################################### END OF PROCESS CHUNK ########################################################
##################################################################################################################################

### Function called in Main Logic Section

Define a codeblock to avoid repeating it twice when to_profvis is TRUE and again if FALSE

Makes it easier to maintain as well, since we only need to modify one section instead of two

In [127]:
main_logic_func <- function() {
  # Start main execution logic
  ####################################################################################################################################
  ################################################## START OF SPLIT AND SAVE PART ####################################################
  ####################################################################################################################################

  separator <- if (file_type == ".tsv") "\t" else ","

  # Step 1: Read the header of the full claims file
  full_header <<- fread(
    file = full_claims_file,
    nrows = 1, colClasses = "character",
    header = TRUE, encoding = encode # , sep = separator
  )

  # Step 2: Check if the split part file already exists. If not, read the full claims file.
  if (!file.exists(here(raw_claims_parts_path, paste0(
    full_claims_prefix, year_to_load,
    "_part_", sprintf("%02d", split_parts),
    "_of_", split_parts, ".rds"
  )))) {
    # Read the full file into memory

    full_file <<- fread(
      file = full_claims_file, colClasses = "character",
      header = TRUE, encoding = encode # , sep = separator
    )
  }

  # Function to split the file into chunks and save them
  split_and_save <- function(split_and_save_part) {
    rows_per_part <- ceiling(total_rows / split_parts) # Calculate how many rows per part
    chunk_file <- here(raw_claims_parts_path, paste0(
      full_claims_prefix, year_to_load,
      "_part_", sprintf("%02d", split_and_save_part),
      "_of_", split_parts, ".rds"
    ))

    # Only process if the part does not already exist
    if (!file.exists(chunk_file)) {
      # Determine start and end rows for this chunk
      start_row <- (split_and_save_part - 1) * rows_per_part + 1
      end_row <- min(split_and_save_part * rows_per_part, total_rows)

      # Extract chunk of data for processing
      chunk_dt <- full_file[start_row:end_row]

      # Debug print the first 2 rows if in debug mode
      if (to_debug) print(head(chunk_dt), 2)

      # Save the chunk as an RDS file
      saveRDS(chunk_dt, chunk_file, compress = TRUE)

      # Optionally reduce memory usage
      if (to_dec_mem_usage) rm(chunk_dt)
      if (to_dec_mem_usage) gc()

      # Save processing time for this part
      split_processing_times[[split_loop_part]] <- as.numeric(
        difftime(Sys.time(), start_time, units = "secs")
      )

      # Print status update and estimate remaining time
      print_status_update(split_loop_part, split_parts, split_processing_times, "split")
    }
  }

  # Step 3: Split the file into parts and save them
  start_time <<- Sys.time() # Record start time
  for (split_loop_part in 1:split_parts) split_and_save(split_loop_part)

  ####################################################################################################################################
  ################################################## END OF SPLIT AND SAVE PART ######################################################
  ####################################################################################################################################

  # Step 4: Set up parallelization if required (Unix and non-Unix systems handled differently)
  if (to_parallel && !is_unix) plan(multisession, workers = nthreads)

  # Step 5: Loop through each part and process the partial files
  for (loop_part in 1:split_parts) {
    ##################################################################################################################################
    ################################################### START OF PROCESS PART ########################################################
    ##################################################################################################################################

    start_time <- Sys.time() # Record start time for processing
    partial_claims_file <<- here(raw_claims_parts_path, paste0(
      full_claims_prefix, year_to_load,
      "_part_", sprintf("%02d", loop_part), "_of_", split_parts, ".rds"
    ))

    # Step 6: Handle sampling logic if applicable
    if (to_sample) {
      sampled_claims_file <<- here(raw_claims_samples_path, paste0(
        "sampled_claims_", year_to_load, "_", sample_size,
        "_part_", sprintf("%02d", loop_part), "_of_", split_parts, ".rds"
      ))
      ensure_sample_files_exist(loop_part) # Ensure sample files exist
    }

    # Step 7: Read the appropriate file (sample or full)
    read_result <- read_appropriate_file(loop_part, to_sample)
    read_in_dt <- read_result$read_result_dt # The data to process
    read_in_replacement_summary <- read_result$read_result_replacement_summary # Any replacements summary

    ##################################################################################################################################
    ############################################ START OF PARALLELIZE AND SUMMARIZE DATA #############################################
    ##################################################################################################################################

    # Step 8: Split the data into chunks for parallel processing
    chunk_size <- ceiling(nrow(read_in_dt) / nthreads)
    chunks <- split(read_in_dt, rep(1:nthreads, each = chunk_size, length.out = nrow(read_in_dt)))

    # Step 9: Apply parallel processing (Unix uses 'mclapply', non-Unix uses 'future_lapply')
    if (to_parallel && is_unix) {
      if (to_debug) message("Conducting mclapply")
      parallel_results <- mclapply(
        chunks, process_chunk,
        mc.cores = nthreads,
        to_view_checks = to_view_checks,
        rvs_icd9 = rvs_icd9,
        tdrg_icd10 = tdrg_icd10,
        acc_pdx = acc_pdx
      )
    } else if (to_parallel && !is_unix) {
      if (to_debug) message("Conducting future_lapply")
      parallel_results <- future_lapply(
        chunks, process_chunk,
        to_view_checks = to_view_checks,
        rvs_icd9 = rvs_icd9,
        tdrg_icd10 = tdrg_icd10,
        acc_pdx = acc_pdx,
        future.seed = global_seed
      )
    } else {
      if (to_debug) message("Conducting lapply")
      parallel_results <- lapply(
        chunks, process_chunk,
        to_view_checks = to_view_checks,
        rvs_icd9 = rvs_icd9,
        tdrg_icd10 = tdrg_icd10,
        acc_pdx = acc_pdx
      )
    }

    # Step 10: Combine results from all parallel chunks
    parallel_summaries <- lapply(parallel_results, function(res) res$return_summary)
    rbound_dt <- rbindlist(lapply(parallel_results, function(res) res$return_chunk))

    combined_chunk_summary <- combine_chunk_summaries(
      parallel_summaries, tmp_nrow
    )

    # Step 11: Check for invalid primary diagnoses (PDx) and update the summary
    acc_pdx_env <- new.env(hash = TRUE, parent = emptyenv())
    for (code in acc_pdx) {
      assign(code, TRUE, envir = acc_pdx_env)
    }
    invalid_pdx_indices <- which(
      !is.na(rbound_dt$pdx) & rbound_dt$pdx != "" &
        !sapply(rbound_dt$pdx, function(x) exists(x, acc_pdx_env))
    )
    if (length(invalid_pdx_indices) > 0) {
      message(paste("Invalid PDx found:", rbound_dt$pdx[invalid_pdx_indices]))
      combined_chunk_summary$pdx_success <- FALSE
    } else {
      combined_chunk_summary$pdx_success <- TRUE
    }

    if (to_dec_mem_usage) gc() # Reduce memory usage if necessary

    ##################################################################################################################################
    ############################################## END OF PARALLELIZE AND SUMMARIZE DATA #############################################
    ##################################################################################################################################

    summarized_dt <- rbound_dt # Store the summarized data
    combined_parallel_summary <- combined_chunk_summary # Store combined summary
    combined_parallel_summary$replacement_summary <- read_in_replacement_summary

    # Step 12: Write processed data to checkpoint file if required
    if (to_write) {
      saveRDS(
        summarized_dt, here(checkpoint_1_path, paste0(
          checkpoint_1_prefix, year_to_load, suffix,
          "part_", sprintf("%02d", loop_part), "_of_", split_parts, ".rds"
        )),
        compress = TRUE
      )
    }

    # Step 13: Collect summaries for each part
    all_parts_summaries[[loop_part]] <- combined_parallel_summary
    processing_times[[loop_part]] <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))

    # Step 14: Update status and ETA
    print_status_update(loop_part, split_parts, processing_times, "clean")

    if (loop_part == 1) dim_dt <<- dim(summarized_dt)
    nrow_end[[loop_part]] <<- nrow(summarized_dt)

    # Step 15: Clean up memory after processing each part
    if (to_dec_mem_usage) {
      rm(read_in_dt, rbound_dt, summarized_dt)
      gc()
    }
  }

  # Step 16: Ensure that row counts match between parts
  for (nrow_part in 1:split_parts) {
    if (nrow_start[[nrow_part]] != nrow_end[[nrow_part]]) {
      warning(
        "WARNING: Row Count Mismatch! Part ", nrow_part,
        " has ", nrow_start[[nrow_part]], " starting rows and ",
        nrow_end[[nrow_part]], " ending rows\n"
      )
      stop("ERROR: Row Count Mismatch")
    }
  }
  message("\nRow Counts Match for All Parts\n")

  # Step 17: Combine all parts into a master data table if required
  if (to_combine) {
    for (read_part in 1:split_parts) {
      master_dt_list[[read_part]] <- readRDS(here(checkpoint_1_path, paste0(
        checkpoint_1_prefix, year_to_load, suffix,
        "part_", sprintf("%02d", read_part), "_of_", split_parts, ".rds"
      )))
    }
    master_dt <<- rbindlist(master_dt_list)

    if (to_debug) print(head(master_dt))
    if (to_dec_mem_usage) {
      if (to_group) rm(master_dt_list) else rm(master_dt_list)
      gc()
    }
    if (to_write) {
      saveRDS(master_dt, here(checkpoint_2_path, paste0(
        checkpoint_2_prefix, year_to_load, suffix, ".rds"
      )), compress = TRUE)
    }
  }

  # Step 18: Print final summaries
  print_summary_tables(
    combine_parts_summaries(all_parts_summaries, tmp_nrow),
    end_nrow
  )

  # Step 19: End parallelization session if on non-Unix system
  if (to_parallel && !is_unix) plan(sequential)

  # Return master data table for debugging purposes
  if (to_debug) {
    return(master_dt)
  }
}

## Main Processing Section

### Read, Process, and Export Data

Calls main_logic_func()

In [128]:
# Initialize Variables
all_parts_summaries <- master_dt_list <- list() # initialize lists
# if (to_group) master_grouper_input_list <- list()
dim_dt <- vector() # initialize vector for dt dimensions
processing_times <- split_processing_times <- nrow_start <- nrow_end <- numeric(split_parts)
master_dt <- data.table() # initialize data.tables
# if (to_group) master_grouper_input_dt <- data.table() # initialize data.tables
nthreads <- parallelly::availableCores() # detect available threads
message(paste0("Utilizing ", nthreads / 2, " cores (", nthreads, " threads)\n"))

# Call the main function with or without profvis
if (to_profvis) {
  saveWidget(profvis({
    main_logic_func()
  }), profvis_fpath)
} else {
  main_logic_func()
}

Utilizing 4 cores (8 threads)

Finished cleaning 15 of 15 parts in 37s (ETA 0s)

Row Counts Match for All Parts

Rename Success:
 TRUE

Table: ICD Normalized Text for clin c1 & c2 Before Splitting

|old_code     |new_code | diff_chars|
|:------------|:--------|----------:|
|B05.2+J17.1* |B052J171 |          4|
|I63.9+G46.7* |I639G467 |          4|
|B37.1+J17.2* |B371J172 |          4|
|I67.9+G46.8* |I679G468 |          4|
|E14.2+N08.3* |E142N083 |          4|
|A37.9+J17.0* |A379J170 |          4|
|A01.0+J17.0* |A010J170 |          4|
|E11.2+N08.3* |E112N083 |          4|
|B06.8+J17.1* |B068J171 |          4|
|D63.8*       |D638     |          2|


Table: Unique Before and After Mappings for Patient Type

|Original |Mapped |
|:--------|:------|
|DD       |D      |
|MM       |M      |


Table: Unique Before and After Mappings for Memcat Parent

|Original             |Mapped |
|:--------------------|:------|
|INDIRECT CONTRIBUTOR |I      |
|DIRECT CONTRIBUTOR   |D      |
|NA                   |NA     |


Table: Unique Before and After Mappings for Memcat Child

|Original                                        |Mapped |
|:-----------------------------------------------|:------|
|SPONSORED                                       |5      |
|INDIGENT                                        |4      |
|EMPLOYED PRIVATE                                |1      |
|SELF-EARNING INDIVIDUAL                         |2      |
|SELF EARNING INDIVIDUAL                         |2      |
|LIFETIME MEMBER                                 |3      |
|SENIOR CITIZEN                                  |6      |
|EMPLOYED GOVERNMENT                             |1      |
|MIGRANT WORKER                                  |2      |
|FILIPINOS WITH DUAL CITIZENSHIP / LIVING ABROAD |2      |
|FOREIGN NATIONAL                                |2      |
|NA                                              |NA     |
|HOUSEHOLD HELP/KASAMBAHAY                       |1      |
|PROFESSIONAL PRACTITIONER                       |2      |


Table: Unique Before and After Mappings for Discharge

|Original |Mapped |
|:--------|:------|
|I        |1      |
|R        |1      |
|E        |9      |
|H        |2      |
|NA       |NA     |
|T        |4      |
|A        |3      |


Table: Unique Before and After Mappings for Claim Status

|Original     |Mapped |
|:------------|:------|
|PAID         |G      |
|DENIED       |D      |
|RTH          |R      |
|IN-PROCESS   |I      |
|APRV4PAYMENT |G      |

No RVS codes discarded.



Table: Empty Strings Replaced (Zeroth Set)

|Column               |Empty_Replaced_Percentage |NA_Replaced_Percentage |Character0_Replaced_Percentage |
|:--------------------|:-------------------------|:----------------------|:------------------------------|
|SECONDARY_ILLNESS    |96.65%                    |0.00%                  |0.00%                          |
|REFILE_DATE          |92.05%                    |0.00%                  |0.00%                          |
|PATIENT_RELATIONSHIP |74.06%                    |0.00%                  |0.00%                          |
|RVSCODES_ITEM7       |20.49%                    |0.00%                  |0.00%                          |
|CHECK_DATE           |4.81%                     |0.00%                  |0.00%                          |
|ICDCODES_ITEM7       |2.29%                     |0.03%                  |0.00%                          |
|ROOM_TYPE            |0.37%                     |0.00%                  |0.00%                          |
|PATIENT_DISPOSITION  |0.09%                     |0.00%                  |0.00%                          |
|PRIMARY_ILLNESS      |0.02%                     |0.00%                  |0.00%                          |
|HCP_NO_LIST          |0.02%                     |0.00%                  |0.00%                          |


Table: Empty Strings Replaced (First Set)

|Column   |Empty_Replaced_Percentage |NA_Replaced_Percentage |Character0_Replaced_Percentage |
|:--------|:-------------------------|:----------------------|:------------------------------|
|c2       |0.00%                     |96.65%                 |0.00%                          |
|c2_orig  |0.00%                     |96.65%                 |0.00%                          |
|clin_rvs |0.00%                     |20.48%                 |0.00%                          |
|c1       |0.00%                     |0.02%                  |0.00%                          |
|c1_orig  |0.00%                     |0.02%                  |0.00%                          |

No empty strings replaced in the second set.

There are 3323 RVS codes without an ICD-9CM equivalent recognized by the TDRG ICD9CM
There are 691 unique RVS codes that appear in the claims.
Of these, 642 (92.91%) have a mapping to an ICD-9-CM code.
Of these, there are 134 (19.39%) with more than one ICD9 equivalent recognized by the Thai ICD9 library.


There are 3199 unique entries for ICD-10 codes, of which 1934 (60.46%) are directly in the Thai ICD-10 library.
The modifications led to a total of 2359 codes being mapped to an equivalent in the Thai ICD10 library.
Out of these, 425 were modified to match.
There are 840 codes that could not be mapped to the Thai ICD10 library.

Number of rows with phl_icd10 length greater than 5: 130 of 425 rows

Table: Modified ICD-10 codes ordered by descending NChar distance

|phl_icd10 |tdrg_icd10 | char_diff|
|:---------|:----------|---------:|
|J1899,Y95 |J189       |         5|
|E142NO83  |E142       |         4|
|C19IP2    |C19        |         3|
|C19IP1    |C19        |         3|
|C19IP3    |C19        |         3|
|C19IP4    |C19        |         3|
|C19PP1    |C19        |         3|
|S81011A   |S810       |         3|
|S91331A   |S913       |         3|
|C19AT1    |C19        |         3|


Table: Invalid ICD-10 Codes Not Found in Thai Library

|code  |source   | count|
|:-----|:--------|-----:|
|NA    |clin_icd | 20316|
|90935 |clin_icd | 10914|
|99460 |clin_icd |  3437|
|NSD01 |clin_icd |  1466|
|MCP01 |clin_icd |   895|
|96408 |clin_icd |   824|
|A971  |clin_icd |   774|
|59513 |clin_icd |   664|
|77418 |clin_icd |   534|
|U072  |clin_icd |   435|

All PDx's are in list of acceptable PDx's:
 TRUE

In [149]:
print(head(readRDS(here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, ".rds"))), 100))

     id_year              id_series                           id_pin   date_adm
       <int>                 <char>                           <char>     <char>
  1:    2022 7009017009013012209007 12E7C6E880E651AB2AE91954A6753393 09/05/2022
  2:    2022 9103789103012902203019 481266642E0D8BB53DF37A196E87EDC1 07/11/2022
  3:    2022 5101955101060303201015 FE6730FFDE7474EAD38F330A6C4B403F 10/03/2022
  4:    2022 6101306101130203211016 565711CAE81EC5F7DB4B3B031478F47E 12/14/2022
  5:    2022 9003479003022802203009 21BEAAB1E4AD4841C85914954A97EB71 07/28/2022
  6:    2022 5004065004002212204005 4F2CA837C4E306571C8B5DA972AF273E 10/19/2022
  7:    2022 5008465008103103218005 A15CB8950194BB4C220ACA2D061CE0D1 12/17/2022
  8:    2022 4106334106031902206014 5632C6CF96719B208D7479DFB502D968 07/07/2022
  9:    2022 6000966000212602220006 0B0FC287DC77C68884E6BBFFA10192CE 04/22/2022
 10:    2022 0205910205140103215020 522EE8613C35CF6E141FDE5D95365490 11/18/2022
 11:    2022 8102378102072802202018 A0A8E7A8C5C062E3168BA3CE3364E4E1 07/07/2022
 12:    2022 0001640001032203201000 9ACEE775F4BF1BC828B94D694A031727 08/07/2022
 13:    2022 7004257004172212214007 1925696451197C771B5D1AFF1BF48834 12/05/2022
 14:    2022 0202460202052702202020 3DA1B76DD73962F28603536C428C697E 07/16/2022
 15:    2022 0008020008031502208000 32C4D885B2018B1851F599C30E98D818 04/04/2022
 16:    2022 0102420102121112212010 A37519ACE215E23580EAE77510E0F891 09/16/2022
 17:    2022 5109585109040302209015 387EA666984E952E72154B99771BFD12 02/03/2022
 18:    2022 3007333007112802217003 A0FB0152B3CF2C879F6C4416EAE8F116 08/03/2022
 19:    2022 4106774106020203206014 7D1186AD4C66CD34C883F1035F3BB443 11/24/2022
 20:    2022 3008893008140103218003 34DF0629DAB40D94B447AAD847AB5F92 09/12/2022
 21:    2022 4308524308092602208034 E0446B2EE71E5DF5F5E2E72ED8A7CBAD 05/10/2022
 22:    2022 9106219106052012206019 2081633E387BC9008D6C55BB4CB0E7F5 08/29/2022
 23:    2022 6101816101241203221016 7A10A284E5B6F17C688D404503C172B8 10/30/2022
 24:    2022 0202560202113302212020 B851D8A7EC7175DDD41E43F28AA26CAE 02/27/2022
 25:    2022 1101361101060103201011 2BFD3D40BDE1F26CAF931C2968B31873 12/14/2022
 26:    2022 1005241005040112205001 88B535D7D0477DE61F12AF3419C617D9 09/29/2022
 27:    2022 1308931308001602208031 BE72E0A3745A577E73357099749B10E8 05/24/2022
 28:    2022 2000882000292702220002 F055C34D1C11C48674B187FB72E80BE4 06/29/2022
 29:    2022 2205142205002702205022 5F3B322651804B4911B658A412E743E3 06/10/2022
 30:    2022 6002766002031702202006 9453256166187DF01DEB670BC61974B0 07/04/2022
 31:    2022 4107124107031902207014 B3C43D85619FCF3010E8030DE0FE9B62 08/02/2022
 32:    2022 3003433003071902203003 B9172B330736E2AD7BB5D7357BE1EB25 08/06/2022
 33:    2022 3104393104032202204013 DC43567DD0A8596581AB556261184994 02/15/2022
 34:    2022 5001815001032212201005 C83489DFB29B6ECBEB0DD60426D7AB53 11/26/2022
 35:    2022 1008881008131602218001 7E935486B6579F6B7AAA39B1E9E98CCD 03/03/2022
 36:    2022 1005191005150203215001 4F5F705CE316553DE24CDB91206CEE45 12/08/2022
 37:    2022 8007008007101012217008 5826F473ED415A912531498D9B81E00F 08/19/2022
 38:    2022 9002039002101902212009 3A2E7D03C620A4A2A0BA60FD43383837 07/19/2022
 39:    2022 1301541301111103211031 3C16A3F1FE6C679104754C01DF2B06B6 12/16/2022
 40:    2022 7005897005061802205007 92D8F3C4ADAF6D0BEC5C663AE34E1CC0 07/06/2022
 41:    2022 1105661105072402205011 0C5AA402CDC89E749782593C97F22F18 04/06/2022
 42:    2022 1302251302012103202031 E9362706D0562E13F3353BBAAF4ABAD0 10/03/2022
 43:    2022 2107292107051302207012 D031673B2BC9A1B8FB6258B2A8D7DABB 03/08/2022
 44:    2022 4102574102103212212014 987A0BEF3FEC18F237EE90C249B2C697 08/26/2022
 45:    2022 8009518009021902209008 3080C757FD67786C42BEBAC3800F132D 07/29/2022
 46:    2022 1102781102162802212011 15A23E958582FBF43C8C5A73C6C66D7F 06/20/2022
 47:    2022 7107557107042302207017 24FD3956FDFE804EA88891E38B2DA3DA 02/11/2022
 48:    2022 0207420207042103207020 6739BB10E25BB9CAE9C66CD720C198B1 12/03/2022
 49:    2022 3307093307052112207033 335294315CC1400FCF1C4C48581C98EA 11/02/2022
 50:    2022 1004331004050012204001 DD1A5E191272FA1A476CF012BEB440D1 08/10/2022
 51:    2022 8004818004110702214008 0BFCCA12DEA1E1C7DE569404A3255C79 05/17/2022
 52:    2022 1003101003103103213001 1965A1948525398A1AB317F37F7B2338 12/03/2022
 53:    2022 3205283205091702205023 373C38933ACEA4D4ED3BDE3760BD7421 06/21/2022
 54:    2022 3102203102091802202013 8370683B6AC9E55F2D0AB27B3148ABEE 07/01/2022
 55:    2022 1002531002120602212001 5355BBF7D75DD2C74D8793B298C320AD 04/08/2022
 56:    2022 1008391008142902218001 E5AB66BE087D07025FCFB29FE1600785 07/02/2022
 57:    2022 5106285106102502216015 9B6C26C3EDC9D5B67B7D7688A3294818 05/02/2022
 58:    2022 6005216005090302205006 094BF90320C8D01EB9DE1845E5E381AA 02/19/2022
 59:    2022 1101581101110702211011 3DDF0A667570861202E8D2D60044A207 06/14/2022
 60:    2022 5101555101252802221015 82569B690563EE2EC731B2A0C143AD82 08/12/2022
 61:    2022 0101590101162212211010 955327A4BEAC739310C822C3A634174F 11/10/2022
 62:    2022 9008049008090112208009 7969BF4BAF973685FE4AE21A74D57942 10/27/2022
 63:    2022 2109832109002702209012 C54C4FCE47FBC7E5417EA61F22EBDAD9 06/30/2022
 64:    2022 6105366105101302215016 0E600FCB122B36BADFBDE72B4B0B12FE 01/10/2022
 65:    2022 7002667002013502202007 6304E49F08762C5904FDAB7A1AFC0755 03/31/2022
 66:    2022 8307108307090602207038 38EAB25984E3E074E844EC30256B183B 04/23/2022
 67:    2022 0101070101012702201010 17E251723F136C17384EF3ABE339EAA6 06/20/2022
 68:    2022 3005603005161702215003 757509FEEE0E152D31048B513643BF16 06/13/2022
 69:    2022 9100409100132112210019 51BE4ABFB1F5FB0AC35EAB45B2ACC199 11/08/2022
 70:    2022 3201663201171802211023 9815FE6F6839933D06621C9164F34A3B 06/11/2022
 71:    2022 6103166103032602203016 458BFD6028F52A986C67FE8D5B0894FB 06/09/2022
 72:    2022 3009073009011402209003 25DF97E9014579D9D5FC79C3AA014798 03/08/2022
 73:    2022 0103990103001202203010 16F02241347A45FFB428C3A096D53BCC 01/04/2022
 74:    2022 1207291207090212207021 3520310BD8DD3A6659E16328337C3228 10/14/2022
 75:    2022 9005639005012212205009 B64CCE783546DEAB85DC6ADCE0153319 10/23/2022
 76:    2022 9008379008011402208009 DF7FE6F537ECDF3DA8C2DE44D6BC1937 04/01/2022
 77:    2022 4000484000113212210004 8CC26AA956B728EF5F68B606EE41B690 12/16/2022
 78:    2022 7107237107092112207017 175902812FB3BA4A3D6FA89FA2514957 11/03/2022
 79:    2022 3203553203022202203023 F64B52FC0095F98C801316455498FF77 01/22/2022
 80:    2022 3001523001131112211003 25FB755DB4B72AB45F0EBB6F58685CCA 09/26/2022
 81:    2022 7001967001251112221007 E3BBD05F61B552ECA78F57888AEAEBC9 09/02/2022
 82:    2022 0202810202160203212020 A4FB610E067C7747FD3CACF18D7B3F54 12/04/2022
 83:    2022 5105845105120902215015 0A60F80B8A737AB3864F430556E1C05F 06/07/2022
 84:    2022 6102616102060902202016 01F89A1A125CDE9A3B950188E7256A28 08/27/2022
 85:    2022 7003767003191802213007 3A65E05959FD92F0DB251FF7257E406E 07/21/2022
 86:    2022 6403636403092602203046 51EF6B0FA2EA912BA73FA99EFA3ED866 04/13/2022
 87:    2022 8002958002012802202008 3B1D2543E5D9D397B9A6A09AF31AAC86 08/20/2022
 88:    2022 5202115202081602202025 BE4E3E65EA5124B35331E0E1F95D02A1 06/17/2022
 89:    2022 2205952205121902215022 D17441A6BE7084FBE6E02DBACECB6E90 07/14/2022
 90:    2022 6003946003161602213006 CF0995E66D29649574AEF2BA4D1665D3 05/25/2022
 91:    2022 3003663003102112213003 9F055EB70DFDF628754CA8DF57A480C1 10/01/2022
 92:    2022 0107950107011502207010 62A94E9D9F5CFB0594B29FDF7E22E427 01/19/2022
 93:    2022 3106343106062802206013 54DB5A4DFF756B959C3098C9EBBE8ECE 07/21/2022
 94:    2022 2008452008181112218002 A80C9450BE742A466DC28428FD88AE5A 11/12/2022
 95:    2022 7107067107002902207017 CEE5E5C0EADB2FAD7261FB4B512EC003 07/25/2022
 96:    2022 9106979106171302216019 84073FF602D664E9BBE71518CF6552E3 02/23/2022
 97:    2022 4100314100170302210014 6DDF4C8DC511D5545641E20DAF0796CD 01/29/2022
 98:    2022 0102490102051212202010 3DD6CB6A8A6632F532CC35F3B97EA822 09/03/2022
 99:    2022 5008755008182102218005 C527643FEA3D2CE74EA24029F296F9C9 01/12/2022
100:    2022 6103816103062802203016 005D1FD6DF778FA4EC4CBCECF2C1C778 07/24/2022
     id_year              id_series                           id_pin   date_adm
     time_adm   date_dis time_dis   date_rec   date_ref date_check   date_ext
       <char>     <char>   <char>     <char>     <char>     <char>     <char>
  1:    11:30 09/06/2022    16:17 10/31/2022       <NA> 12/13/2022 08/03/2024
  2:    17:02 07/13/2022    15:25 09/21/2022       <NA> 09/14/2023 08/03/2024
  3:    13:26 10/03/2022    13:26 03/06/2023       <NA>       <NA> 08/03/2024
  4:    21:10 12/16/2022    15:17 02/03/2023       <NA> 02/08/2023 08/03/2024
  5:    10:24 07/28/2022    23:00 08/22/2022       <NA> 03/10/2023 08/03/2024
  6:    14:26 10/29/2022    19:00 12/20/2022       <NA> 01/20/2023 08/03/2024
  7:    06:30 12/18/2022    10:20 01/30/2023       <NA> 02/15/2023 08/03/2024
  8:    09:00 07/08/2022    16:46 09/13/2022       <NA> 11/14/2022 08/03/2024
  9:    10:48 04/23/2022    11:43 06/21/2022       <NA> 07/28/2022 08/03/2024
 10:    21:45 11/18/2022    22:05 01/04/2023       <NA> 02/23/2023 08/03/2024
 11:    13:48 07/07/2022    14:03 08/27/2022 10/27/2022 11/25/2022 08/03/2024
 12:    16:34 08/08/2022    22:09 02/23/2023       <NA>       <NA> 08/03/2024
 13:    10:20 12/05/2022    16:31 12/27/2022       <NA> 01/25/2023 08/03/2024
 14:    08:21 07/16/2022    14:13 07/25/2022       <NA> 07/29/2022 08/03/2024
 15:    05:49 04/14/2022    09:49 05/13/2022 06/14/2022 07/04/2022 08/03/2024
 16:    14:17 09/16/2022    14:30 10/06/2022       <NA> 11/16/2022 08/03/2024
 17:    08:00 02/14/2022    12:00 03/04/2022       <NA> 04/28/2022 08/03/2024
 18:    05:25 08/03/2022    09:25 08/21/2022       <NA> 09/06/2022 08/03/2024
 19:    22:29 11/29/2022    13:10 02/02/2023       <NA> 03/29/2023 08/03/2024
 20:    15:12 09/12/2022    20:12 01/04/2023       <NA> 02/02/2023 08/03/2024
 21:    21:05 05/12/2022    08:00 06/29/2022       <NA> 07/15/2022 08/03/2024
 22:    18:00 08/29/2022    23:00 10/25/2022       <NA> 12/01/2022 08/03/2024
 23:    11:30 10/30/2022    12:30 02/14/2023       <NA> 03/24/2023 08/03/2024
 24:    20:00 02/28/2022    00:00 03/31/2022       <NA> 08/18/2022 08/03/2024
 25:    13:20 12/16/2022    13:49 01/06/2023       <NA> 02/16/2023 08/03/2024
 26:    11:00 09/29/2022    11:10 11/04/2022       <NA> 02/03/2023 08/03/2024
 27:    14:12 05/27/2022    13:38 06/10/2022       <NA> 06/29/2022 08/03/2024
 28:    11:25 06/30/2022    13:30 07/29/2022       <NA> 08/11/2022 08/03/2024
 29:    19:00 06/12/2022    16:00 07/20/2022       <NA> 08/02/2022 08/03/2024
 30:    08:19 07/04/2022    13:20 07/13/2022       <NA> 07/22/2022 08/03/2024
 31:    00:35 08/07/2022    12:28 09/13/2022       <NA> 10/12/2022 08/03/2024
 32:    14:00 08/06/2022    18:00 09/17/2022       <NA> 11/11/2022 08/03/2024
 33:    07:00 02/15/2022    11:00 02/23/2022       <NA> 04/08/2022 08/03/2024
 34:    00:13 11/27/2022    17:00 12/23/2022       <NA> 02/15/2023 08/03/2024
 35:    08:47 03/20/2022    15:54 06/13/2022       <NA> 07/11/2022 08/03/2024
 36:    11:11 12/08/2022    22:00 02/05/2023       <NA> 03/24/2023 08/03/2024
 37:    10:42 08/26/2022    09:46 10/10/2022       <NA> 10/27/2022 08/03/2024
 38:    23:00 07/24/2022    13:30 09/10/2022       <NA> 10/17/2022 08/03/2024
 39:    08:30 12/16/2022    09:40 01/11/2023       <NA> 02/02/2023 08/03/2024
 40:    12:00 07/08/2022    12:55 08/16/2022       <NA> 09/12/2022 08/03/2024
 41:    07:35 04/08/2022    15:45 04/27/2022       <NA> 07/19/2022 08/03/2024
 42:    13:00 10/03/2022    13:30 01/21/2023       <NA> 02/10/2023 08/03/2024
 43:    14:05 03/08/2022    16:28 03/15/2022       <NA> 03/29/2022 08/03/2024
 44:    19:05 09/02/2022    14:30 12/30/2022 04/20/2023 07/07/2023 08/03/2024
 45:    08:00 08/01/2022    09:00 09/12/2022       <NA> 10/07/2022 08/03/2024
 46:    10:47 06/27/2022    18:40 08/26/2022       <NA> 10/11/2022 08/03/2024
 47:    07:15 02/11/2022    07:30 03/24/2022       <NA> 04/19/2022 08/03/2024
 48:    09:33 12/03/2022    13:33 01/24/2023       <NA> 02/10/2023 08/03/2024
 49:    10:45 11/02/2022    13:45 11/25/2022       <NA> 12/15/2022 08/03/2024
 50:    20:50 08/13/2022    17:30 10/05/2022       <NA> 10/18/2022 08/03/2024
 51:    06:40 05/17/2022    09:40 07/01/2022       <NA> 07/21/2022 08/03/2024
 52:    18:00 12/06/2022    14:40 01/30/2023       <NA> 02/23/2023 08/03/2024
 53:    07:30 06/21/2022    10:00 07/19/2022       <NA> 08/17/2022 08/03/2024
 54:    11:10 07/15/2022    15:10 08/19/2022       <NA> 09/02/2022 08/03/2024
 55:    10:11 04/10/2022    23:10 06/02/2022       <NA> 06/17/2022 08/03/2024
 56:    06:45 07/30/2022    10:35 09/24/2022       <NA> 10/18/2022 08/03/2024
 57:    08:30 05/11/2022    14:50 05/20/2022       <NA> 06/29/2022 08/03/2024
 58:    01:00 02/20/2022    09:00 03/09/2022 06/23/2022       <NA> 08/03/2024
 59:    16:35 06/14/2022    20:35 07/01/2022       <NA> 07/15/2022 08/03/2024
 60:    12:00 08/12/2022    18:00 08/25/2022       <NA> 09/09/2022 08/03/2024
 61:    08:28 11/10/2022    14:28 12/26/2022       <NA> 02/23/2023 08/03/2024
 62:    12:51 10/29/2022    16:15 11/09/2022       <NA> 11/25/2022 08/03/2024
 63:    10:45 06/30/2022    11:15 07/20/2022       <NA> 08/06/2022 08/03/2024
 64:    07:35 01/10/2022    11:35 03/10/2022       <NA> 03/18/2022 08/03/2024
 65:    00:00 03/31/2022    00:00 05/18/2022       <NA> 06/07/2022 08/03/2024
 66:    06:00 04/23/2022    10:00 06/09/2022       <NA> 06/20/2022 08/03/2024
 67:    11:47 06/20/2022    16:03 07/21/2022       <NA> 08/16/2022 08/03/2024
 68:    07:00 06/17/2022    10:00 07/16/2022       <NA> 07/27/2022 08/03/2024
 69:    08:47 11/10/2022    17:40 11/23/2022       <NA> 12/02/2022 08/03/2024
 70:    08:22 06/11/2022    08:22 08/17/2022       <NA> 09/05/2022 08/03/2024
 71:    06:00 06/10/2022    18:00 06/23/2022       <NA> 08/31/2022 08/03/2024
 72:    15:30 03/12/2022    17:00 04/11/2022       <NA> 05/21/2022 08/03/2024
 73:    06:10 01/04/2022    10:10 02/10/2022       <NA> 05/06/2022 08/03/2024
 74:    09:00 10/14/2022    14:10 12/09/2022       <NA> 12/22/2022 08/03/2024
 75:    15:25 10/25/2022    09:45 12/21/2022 02/02/2023       <NA> 08/03/2024
 76:    10:30 04/08/2022    14:30 04/11/2022       <NA> 05/13/2022 08/03/2024
 77:    09:17 12/16/2022    13:46 12/31/2022       <NA> 01/13/2023 08/03/2024
 78:    23:30 11/06/2022    15:03 11/29/2022       <NA> 01/20/2023 08/03/2024
 79:    17:41 01/25/2022    11:14 02/22/2022       <NA> 07/02/2022 08/03/2024
 80:    20:30 10/02/2022    11:18 11/13/2022       <NA> 11/21/2022 08/03/2024
 81:    06:00 09/14/2022    10:00 11/15/2022       <NA> 11/24/2022 08/03/2024
 82:    04:30 12/08/2022    16:00 02/06/2023       <NA> 03/14/2023 08/03/2024
 83:    19:40 06/09/2022    20:40 09/02/2022       <NA> 09/29/2022 08/03/2024
 84:    13:26 08/30/2022    14:05 09/06/2022       <NA> 09/15/2022 08/03/2024
 85:    09:13 07/21/2022    09:18 08/19/2022       <NA> 08/31/2022 08/03/2024
 86:    12:00 04/20/2022    12:00 06/29/2022       <NA> 09/08/2022 08/03/2024
 87:    01:25 08/20/2022    01:28 08/21/2022       <NA> 08/25/2022 08/03/2024
 88:    01:54 06/17/2022    01:57 06/18/2022       <NA> 06/28/2022 08/03/2024
 89:    13:20 07/14/2022    15:10 09/12/2022 11/14/2022 01/19/2023 08/03/2024
 90:    08:00 05/25/2022    09:00 06/16/2022       <NA> 07/15/2022 08/03/2024
 91:    05:09 10/15/2022    09:09 11/20/2022       <NA> 12/07/2022 08/03/2024
 92:    09:29 01/19/2022    13:29 05/11/2022       <NA> 05/24/2022 08/03/2024
 93:    08:00 07/21/2022    17:00 08/26/2022       <NA>       <NA> 08/03/2024
 94:    11:45 11/14/2022    14:00 11/18/2022       <NA> 12/14/2022 08/03/2024
 95:    08:00 07/25/2022    13:00 09/20/2022       <NA> 10/18/2022 08/03/2024
 96:    13:04 02/28/2022    15:03 03/17/2022       <NA> 04/28/2022 08/03/2024
 97:    02:00 01/30/2022    08:00 03/07/2022       <NA> 03/18/2022 08/03/2024
 98:    09:06 09/03/2022    09:06 12/15/2022       <NA> 01/05/2023 08/03/2024
 99:    07:20 01/12/2022    12:20 01/28/2022       <NA> 02/22/2022 08/03/2024
100:    10:02 07/24/2022    10:07 08/26/2022       <NA> 10/25/2022 08/03/2024
     time_adm   date_dis time_dis   date_rec   date_ref date_check   date_ext
     id_hci            id_hcp pat_type pat_rel pat_sex pat_age
     <char>            <char>   <char>  <fctr>  <fctr>   <int>
  1: 440901             34333        D       S       F      33
  2: Z03199             59359        D       C       M       0
  3: Z04606             59139        M    <NA>       M      54
  4: 591201             38465        M    <NA>       F      35
  5: 300806             20840        M    <NA>       M      41
  6: D00060             63160        M    <NA>       M      58
  7: Z03889              4958        M    <NA>       F      22
  8: 130101             69525        M    <NA>       F      60
  9: 971601             15064        D       C       F       0
 10: 830102             35811        M    <NA>       M      31
 11: 313701             46845        M    <NA>       F      42
 12: Z04606       51029|68803        M    <NA>       F      36
 13: 780133             37927        M    <NA>       F      68
 14: 280126              1840        M    <NA>       F      66
 15: Z00107             52106        M    <NA>       F      53
 16: Z05277             30588        M    <NA>       M      36
 17: Z09047             55737        M    <NA>       M      57
 18: 932647             36789        M    <NA>       F      69
 19: 130132       23765|34443        D       C       M       3
 20: 810101             47519        M    <NA>       M      32
 21: M01710             35355        D       C       M       0
 22: 132202             12416        M    <NA>       F      30
 23: 260101             15847        M    <NA>       F      18
 24: 640107             42622        M    <NA>       F      61
 25: Z04939        23174|7668        M    <NA>       F      64
 26: 050102             61814        M    <NA>       M      61
 27: 370101       18418|36373        M    <NA>       F      33
 28: Z08618             47731        D       S       F       0
 29: 030501             67532        D       C       M      13
 30: 280126             42797        M    <NA>       F      67
 31: 210129             33703        M    <NA>       M      64
 32: 300832             33929        M    <NA>       F      77
 33: Z06268             24004        M    <NA>       M      30
 34: M00902             39132        D       C       M       0
 35: 810301       15634|35913        M    <NA>       M      36
 36: 840128 30502|37235|68317        M    <NA>       M      80
 37: R00044             15471        D       C       M       6
 38: 645301             44449        D       C       M       0
 39: Z06885             41997        D       C       M      17
 40: 070901             67018        M    <NA>       M      28
 41: 043301             67584        M    <NA>       F      20
 42: 280102             30232        M    <NA>       F      32
 43: Z07506              3563        M    <NA>       F      44
 44: 640104             47607        M    <NA>       M      41
 45: 441001             31395        D       C       M      10
 46: 642729             47230        M    <NA>       M      69
 47: 200102             66282        M    <NA>       F      49
 48: 200026             42328        M    <NA>       M      66
 49: Z06686             45278        M    <NA>       F      86
 50: Z06268             24004        M    <NA>       F      26
 51: 770101             54893        M    <NA>       M      63
 52: 710201             74684        D       C       F       8
 53: Z00507             24050        M    <NA>       F      64
 54: Z07988             60212        D       S       F      44
 55: Z04719              4306        M    <NA>       F      36
 56: Z06651             45437        M    <NA>       F      29
 57: 950334             22799        D       C       F       0

In [130]:
if (exists("master_dt")) {
  result <- data.table::copy(master_dt)
  rm(master_dt)
  gc()
} else {
  result <- readRDS(here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, ".rds")))
  gc()
}

# Filter rows where any element in c1 contains "c("
if (to_debug) filtered_rows <- as.data.table(result[sapply(c1, function(x) any(grepl("c\\(", x)))])

# Display the structure of the filtered rows
if (to_debug) str(filtered_rows)

# Track invalid age corrections
invalid_age_before <- nrow(result[pat_age < -1 | pat_age > 124, .(id_series)])

pat_age_less_than_or_equal_to_neg_one <- result[pat_age <= -1, .(id_series, pat_age, c1, c2)]
fwrite(pat_age_less_than_or_equal_to_neg_one, here(debug_path, "pat_age_less_than_or_equal_to_neg_one.csv"))

pat_age_between_zero_and_neg_one <- result[pat_age < 0 & pat_age > -1, .(id_series, pat_age, c1, c2)]
fwrite(pat_age_between_zero_and_neg_one, here(debug_path, "pat_age_between_zero_and_neg_one.csv"))

# Use c1_orig and c2_orig as clin_c1 and clin_c2
result[, clin_c1 := c1_orig]
result[, clin_c2 := c2_orig]
result[, c("c1_orig", "c2_orig") := NULL]

# Use icd9_list as clin_proc
result[, clin_proc := icd9_list]
result[, icd9_list := NULL]

# Remove the primary diagnosis from the list of secondary diagnoses
result[, clin_icd := Map(function(pdx_var, sdx_var) sdx_var[sdx_var != pdx_var], pdx, clin_icd)]
result[, clin_sdx := clin_icd]
result[, clin_icd := NULL]

# Ensure that NA check respects the structure of c1 and returns a logical vector of the same length as result
if (to_debug) str(result[sapply(c1, function(x) length(x) > 1 && !all(is.na(unlist(x))))])

if (!"pat_bdate" %in% colnames(dt)) {
  result[, pat_bdate := NA_Date_]
}
date_cols <- c("date_adm", "date_dis", "date_rec", "date_ref", "date_check", "pat_bdate", "date_ext")
# Function to convert and replace dates before 1900-01-01 with NA
convert_and_filter_dates <- function(x) {
  converted_dates <- as.Date(x, format = "%m/%d/%Y")
  # Replace dates before 1900-01-01 with NA
  converted_dates[converted_dates < as.Date("1900-01-01")] <- NA_Date_
  return(converted_dates)
}

if (is_unix) {
  result[, (date_cols) := mclapply(.SD, convert_and_filter_dates, mc.cores = parallel::detectCores()), .SDcols = date_cols]
} else {
  result[, (date_cols) := lapply(.SD, convert_and_filter_dates), .SDcols = date_cols]
}

# Process time columns
time_cols <- c("time_adm", "time_dis")
standardize_time <- function(x) {
  x <- ifelse(is.na(x), "00:00:00", paste0(x, ":00"))
  as.ITime(x)
}
if (is_unix) {
  result[, (time_cols) := mclapply(.SD, standardize_time, mc.cores = parallel::detectCores()), .SDcols = time_cols]
} else {
  result[, (time_cols) := lapply(.SD, standardize_time), .SDcols = time_cols]
}

# Convert ITime object to character in HH:MM:SS format
result[, time_adm := strftime(time_adm, format = "%H:%M:%S")]
result[, time_dis := strftime(time_dis, format = "%H:%M:%S")]

# Convert date_adm and date_dis from Asia/Manila to UTC
result[, date_adm := as.POSIXct(paste(date_adm, time_adm), format = "%Y-%m-%d %H:%M:%S", tz = "Asia/Manila")]
result[, date_dis := as.POSIXct(paste(date_dis, time_dis), format = "%Y-%m-%d %H:%M:%S", tz = "Asia/Manila")]

# Process logical columns
result[, clin_outpatient := as.logical(as.integer(clin_outpatient))]
result[, clin_emergency := as.logical(as.integer(clin_emergency))]

# Process numeric columns
if (!"pat_bwt" %in% colnames(dt)) {
  result[, pat_bwt := NA_real_]
}
num_cols <- c("pat_age", "pat_bwt", "clin_discharge", "claim_payout", "claim_charge", "id_year", "pdx_code")
if (is_unix) {
  result[, (num_cols) := mclapply(.SD, as.numeric, mc.cores = parallel::detectCores()), .SDcols = num_cols]
} else {
  result[, (num_cols) := lapply(.SD, as.numeric), .SDcols = num_cols]
}

# Process integer columns
int_cols <- c("clin_discharge", "id_year", "pdx_code")
if (is_unix) {
  result[, (int_cols) := mclapply(.SD, as.integer, mc.cores = parallel::detectCores()), .SDcols = int_cols]
} else {
  result[, (int_cols) := lapply(.SD, as.integer), .SDcols = int_cols]
}

# Process character columns
char_cols <- c("id_hcp", "pat_type", "clin_acc", "pat_rel", "pat_sex", "pat_memcat_parent", "pat_memcat_child", "claim_status", "pdx")
if (is_unix) {
  result[, (char_cols) := mclapply(.SD, as.character, mc.cores = parallel::detectCores()), .SDcols = char_cols]
} else {
  result[, (char_cols) := lapply(.SD, as.character), .SDcols = char_cols]
}

# Age correction logic
invalid_ages_before_correction <- result[pat_age < 0 | pat_age > 124, .N]
invalid_age_ids_before <- result[pat_age < 0 | pat_age > 124, id_series]

result[pat_age < 0 & pat_age >= -1, pat_age := 0]
result[pat_age < -1 & is.na(pat_bdate), pat_age := NA_integer_]
result[pat_age > 124, pat_age := NA_integer_]
result[pat_age < -1 & !is.na(pat_bdate), pat_age := floor(as.numeric(interval(pat_bdate, date_adm) / years(1)))]

# Regenerate or correct DOB
invalid_bdate_before <- result[is.na(pat_bdate), .N]
invalid_bdate_ids_before <- result[is.na(pat_bdate), id_series]

result[!is.na(pat_age), pat_bdate := dmy(generate_dob(format(pat_bdate, "%Y-%m-%d"), pat_age, format(date_adm, "%Y-%m-%d")))]
result[!is.na(pat_bdate) & pat_bdate <= date_adm, pat_age := floor(as.numeric(interval(pat_bdate, date_adm) / years(1)))]
result[pat_age < -1 & !is.na(pat_bdate) & pat_bdate > date_adm, pat_age := NA_integer_]
result[pat_age > 124 | pat_age < 0, pat_age := NA_integer_]

# Save invalid age rows to CSV
invalid_age_path <- here("data-cleaning", "debug", "invalid_age.csv")
fwrite(data.table(id_series = invalid_age_ids_before), invalid_age_path)

# Save invalid birthdate rows to CSV
invalid_bdate_path <- here("data-cleaning", "debug", "invalid_bdate.csv")
fwrite(data.table(id_series = invalid_bdate_ids_before), invalid_bdate_path)

# Print messages for invalid ages corrected
invalid_ages_after_correction <- result[pat_age < 0 | pat_age > 124, .N]
message(
  "Number of invalid ages corrected: ", invalid_ages_before_correction - invalid_ages_after_correction,
  ". Invalid ages are those with a value less than 0 or greater than 124, which were reset to NA or corrected."
)

# Print messages for invalid birthdates corrected
invalid_bdate_after <- result[is.na(pat_bdate), .N]
message(
  "Number of invalid birthdates corrected: ", invalid_bdate_before - invalid_bdate_after,
  ". Invalid birthdates are missing values (NA), which were corrected based on age and admission dates."
)

result[, pat_ageday := NA_integer_]

# Process pat_ageday for patients younger than 1 year
invalid_ageday_before <- result[!is.na(pat_age) & pat_age >= 0 & pat_age < 1 & is.na(pat_ageday), .N]
invalid_ageday_ids_before <- result[!is.na(pat_age) & pat_age >= 0 & pat_age < 1 & is.na(pat_ageday), id_series]

result[!is.na(pat_age) & pat_age >= 0 & pat_age < 1 & is.na(pat_ageday), pat_ageday := 3]

result[
  !is.na(pat_age) & pat_age >= 0 & pat_age < 1 & !is.na(date_adm) & !is.na(pat_bdate),
  pat_ageday := as.integer(difftime(date_adm, pat_bdate, units = "days"))
]

if ("ageday" %in% colnames(result)) {
  result[, ageday := NULL]
}
gc()
# Print messages for invalid ageday corrections
invalid_ageday_after <- result[!is.na(pat_age) & pat_age >= 0 & pat_age < 1 & is.na(pat_ageday), .N]
message(
  "Number of agedays generated: ", invalid_ageday_before - invalid_ageday_after,
  ". Agedays generated are for where the patient is younger than 1 year, so the exact number of days was generated."
)

# Assuming acc_icd_env is an environment containing acc_icd codes
acc_icd_env <- new.env(hash = TRUE, parent = emptyenv())
for (code in acc_icd) {
  assign(code, TRUE, envir = acc_icd_env)
}

# Modify the data.table operation to use mget with the acc_icd_env
result[, clin_sdx := lapply(clin_sdx, function(row) {
  codes <- unlist(row)
  valid_codes <- codes[!is.na(mget(codes, envir = acc_icd_env, ifnotfound = NA_character_))]
  if (length(valid_codes) > 0) {
    return(valid_codes)
  } else {
    return(NA_character_)
  }
})]

# Optionally unlist each element of clin_sdx
result[, clin_sdx := lapply(clin_sdx, unlist)]

na_replaced_result <- replace_empty_with_na(result)

result <- na_replaced_result$return_data

# Process character columns and convert to UTF-8
if (is_unix) {
  result[, (char_cols) := mclapply(.SD, function(col) iconv(col, from = "", to = "UTF-8"), mc.cores = parallel::detectCores()), .SDcols = char_cols]
} else {
  result[, (char_cols) := lapply(.SD, function(col) iconv(col, from = "", to = "UTF-8")), .SDcols = char_cols]
}

# Function to clean data by handling missing values and replacing invalid entries
clean_data_columns <- function(data) {
  # Identify and process character columns
  char_cols <- names(data)[sapply(data, is.character)]

  # If running on Unix, apply parallel processing for character columns
  if (is_unix) {
    data[, (char_cols) := mclapply(.SD, function(col) {
      # Replace "None" and empty strings with NA in character columns
      col[col %in% c("None", "")] <- NA_character_
      return(col) # Return modified column
    }, mc.cores = parallel::detectCores()), .SDcols = char_cols]
  } else {
    # Apply sequential processing for character columns (non-Unix systems)
    data[, (char_cols) := lapply(.SD, function(col) {
      col[col %in% c("None", "")] <- NA_character_
      return(col) # Return modified column
    }), .SDcols = char_cols]
  }

  # Identify and process numeric columns
  num_cols <- names(data)[sapply(data, is.numeric)]

  # If running on Unix, apply parallel processing for numeric columns
  if (is_unix) {
    data[, (num_cols) := mclapply(.SD, function(col) {
      # Replace NaN values with NA in numeric columns
      col[is.nan(col)] <- NA_real_
      return(col) # Return modified column
    }, mc.cores = parallel::detectCores()), .SDcols = num_cols]
  } else {
    # Apply sequential processing for numeric columns (non-Unix systems)
    data[, (num_cols) := lapply(.SD, function(col) {
      col[is.nan(col)] <- NA_real_
      return(col) # Return modified column
    }), .SDcols = num_cols]
  }

  # Identify and process list columns
  list_cols <- names(data)[sapply(data, is.list)]

  # If running on Unix, apply parallel processing for list columns
  if (is_unix) {
    data[, (list_cols) := mclapply(.SD, function(col) {
      # For each list element, check if it contains characters and replace "None" and empty strings with NA
      lapply(col, function(x) {
        if (is.character(x)) x[x %in% c("None", "")] <- NA_character_
        return(x) # Return modified list element
      })
    }, mc.cores = parallel::detectCores()), .SDcols = list_cols]
  } else {
    # Apply sequential processing for list columns (non-Unix systems)
    data[, (list_cols) := lapply(.SD, function(col) {
      lapply(col, function(x) {
        if (is.character(x)) x[x %in% c("None", "")] <- NA_character_
        return(x) # Return modified list element
      })
    }), .SDcols = list_cols]
  }

  return(data) # Return the cleaned data.table
}

# Apply the cleaning function to the result data.table
result <- clean_data_columns(result)

# Convert string columns to arrays, handling different delimiters: comma, comma with space, single pipe, and double pipe
array_columns <- c("id_hcp")
split_pattern <- "\\s*,\\s*|\\|\\||\\|" # Regex pattern to handle commas, single pipes, and double pipes

if (is_unix) {
  result[, (array_columns) := mclapply(.SD, function(x) {
    # Split based on the specified pattern (comma, comma with space, single pipe, or double pipe)
    x <- strsplit(x, split_pattern)
    # Handle empty or NA entries
    lapply(x, function(y) if (length(y) == 0L || all(is.na(y))) character(0) else y)
  }, mc.cores = parallel::detectCores()), .SDcols = array_columns]
} else {
  result[, (array_columns) := lapply(.SD, function(x) {
    # Split based on the specified pattern (comma, comma with space, single pipe, or double pipe)
    x <- strsplit(x, split_pattern)
    # Handle empty or NA entries
    lapply(x, function(y) if (length(y) == 0L || all(is.na(y))) character(0) else y)
  }), .SDcols = array_columns]
}

# Ensure 'clin_sdx', 'clin_proc', and 'id_hcp' are not NULL
list_columns <- c("clin_sdx", "clin_proc", "id_hcp")
if (is_unix) {
  result[, (list_columns) := mclapply(.SD, function(col) {
    lapply(col, function(x) if (is.null(x) || length(x) == 0L || all(is.na(x))) character(0) else x)
  }, mc.cores = parallel::detectCores()), .SDcols = list_columns]
} else {
  result[, (list_columns) := lapply(.SD, function(col) {
    lapply(col, function(x) if (is.null(x) || length(x) == 0L || all(is.na(x))) character(0) else x)
  }), .SDcols = list_columns]
}

setnames(result, c("pdx", "pdx_code"), c("clin_pdx", "clin_pdx_source"))

setcolorder(result, c(
  "id_year", "id_series", "id_pin", "id_hci", "id_hcp", "date_adm", "time_adm", "date_dis", "time_dis",
  "date_rec", "date_ref", "date_check", "date_ext", "pat_type", "pat_rel", "pat_bdate", "pat_age",
  "pat_ageday", "pat_sex", "pat_bwt", "pat_memcat_parent", "pat_memcat_child", "is_covid", "claim_status", "claim_payout",
  "claim_charge", "clin_discharge", "clin_outpatient", "clin_emergency", "clin_acc", "clin_c1", "c1", "clin_c2", "c2",
  "clin_sdx", "clin_proc", "clin_rvs", "clin_pdx", "clin_pdx_source"
))


# Use a temporary column to avoid self-reference
result[, temp_clin_discharge := as.integer(clin_discharge)]

# Assign the temp column back to clin_discharge
result[, clin_discharge := temp_clin_discharge]

# Remove the temporary column
result[, temp_clin_discharge := NULL]

# # Apply format_id function to each column in parallel or sequentially
# columns_to_format <- c("id_series", "id_pin", "id_hci")
# # Define the format_id function that handles both numerical and alphanumeric formats
# format_id <- function(x) {
#   x <- as.character(x) # Ensure the data is in character format
#   numeric_x <- suppressWarnings(as.numeric(x)) # Try to convert to numeric
#   # Handle numeric values
#   is_numeric <- !is.na(numeric_x) # Identify numeric values
#   x[is_numeric] <- trimws(formatC(numeric_x[is_numeric], format = "f", digits = 0)) # Format numeric values without decimals
#   # Handle non-numeric values (leave as they are)
#   x[!is_numeric] <- trimws(x[!is_numeric])
#   # Return the cleaned-up values
#   return(x)
# }
# # Apply format_id function to each column safely, either in parallel (for Unix) or sequentially (for non-Unix)
# if (is_unix) {
#   # Make a copy of the columns to avoid directly accessing the data.table object in parallel
#   formatted_cols <- mclapply(columns_to_format, function(col) {
#     column_data <- result[[col]] # Extract column data outside the parallel loop
#     return(format_id(column_data)) # Apply format_id to the column
#   }, mc.cores = parallel::detectCores())
# } else {
#   formatted_cols <- lapply(columns_to_format, function(col) {
#     column_data <- result[[col]] # Extract column data
#     return(format_id(column_data)) # Apply format_id to the column
#   })
# }
# # Assign the formatted results back to the respective columns
# for (i in seq_along(columns_to_format)) {
#   result[[columns_to_format[i]]] <- formatted_cols[[i]]
# }

bw_dist <- c(
  runif(2, 0.5, 0.9), # Random birthweight between 0.5 and 0.9 for 2 newborns
  runif(8, 1.1, 1.4), # Random birthweight between 1.1 and 1.4 for 8 newborns
  runif(19, 1.6, 1.9), # Random birthweight between 1.6 and 1.9 for 19 newborns
  runif(95, 2.1, 2.4), # Random birthweight between 2.1 and 2.4 for 95 newborns
  runif(381, 2.6, 2.9), # Random birthweight between 2.6 and 2.9 for 381 newborns
  runif(375, 3.1, 3.4), # Random birthweight between 3.1 and 3.4 for 375 newborns
  runif(115, 3.5, 4.0), # Random birthweight between 3.5 and 4.0 for 115 newborns
  runif(6, 0.5, 4.0) # Random birthweight between 0.5 and 4.0 for 6 newborns
)

# Create the zero_mask condition where pat_age is between 0 and 1 (newborns)
zero_mask <- result[, pat_age >= 0 & pat_age < 1]

# Apply birthweight only if pat_bwt is NA and zero_mask is TRUE
result[(pat_bwt < 0 | is.na(pat_bwt)) & zero_mask, pat_bwt := sapply(.SD$pat_bwt, function(x) sample(bw_dist, 1)), .SDcols = "pat_bwt"]

saveRDS(result, here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, "final", ".rds")), compress = TRUE)

       used    (Mb)  gc trigger (Mb)  max used (Mb)
Ncells 2796592 149.4  5040384   269.2  5040384 269.2
Vcells 7522664  57.4 21596529   164.8 20387082 155.6

Number of invalid ages corrected: 6. Invalid ages are those with a value less than 0 or greater than 124, which were reset to NA or corrected.

Number of invalid birthdates corrected: 20415. Invalid birthdates are missing values (NA), which were corrected based on age and admission dates.

       used    (Mb)  gc trigger (Mb)  max used (Mb)
Ncells 2794465 149.3  5040384   269.2  5040384 269.2
Vcells 6768847  51.7 21596529   164.8 21579085 164.7

Number of agedays generated: 2263. Agedays generated are for where the patient is younger than 1 year, so the exact number of days was generated.

In [131]:
print(head(result))

   id_year              id_series                           id_pin id_hci
     <num>                 <char>                           <char> <char>
1:    2022 7009017009013012209007 12E7C6E880E651AB2AE91954A6753393 440901
2:    2022 9103789103012902203019 481266642E0D8BB53DF37A196E87EDC1 Z03199
3:    2022 5101955101060303201015 FE6730FFDE7474EAD38F330A6C4B403F Z04606
4:    2022 6101306101130203211016 565711CAE81EC5F7DB4B3B031478F47E 591201
5:    2022 9003479003022802203009 21BEAAB1E4AD4841C85914954A97EB71 300806
6:    2022 5004065004002212204005 4F2CA837C4E306571C8B5DA972AF273E D00060
   id_hcp            date_adm time_adm            date_dis time_dis   date_rec
   <list>              <POSc>   <char>              <POSc>   <char>     <Date>
1:  34333 2022-09-05 11:30:00 11:30:00 2022-09-06 16:17:00 16:17:00 2022-10-31
2:  59359 2022-07-11 17:02:00 17:02:00 2022-07-13 15:25:00 15:25:00 2022-09-21
3:  59139 2022-10-03 13:26:00 13:26:00 2022-10-03 13:26:00 13:26:00 2023-03-06
4:  38465 2022-12-14 21:10:00 21:10:00 2022-12-16 15:17:00 15:17:00 2023-02-03
5:  20840 2022-07-28 10:24:00 10:24:00 2022-07-28 23:00:00 23:00:00 2022-08-22
6:  63160 2022-10-19 14:26:00 14:26:00 2022-10-29 19:00:00 19:00:00 2022-12-20
   date_ref date_check   date_ext pat_type pat_rel  pat_bdate pat_age
     <Date>     <Date>     <Date>   <char>  <char>     <Date>   <num>
1:     <NA> 2022-12-13 2024-08-03        D       S 1989-09-05      33
2:     <NA> 2023-09-14 2024-08-03        D       C 2022-06-26       0
3:     <NA>       <NA> 2024-08-03        M    <NA> 1968-10-03      54
4:     <NA> 2023-02-08 2024-08-03        M    <NA> 1987-12-14      35
5:     <NA> 2023-03-10 2024-08-03        M    <NA> 1981-07-28      41
6:     <NA> 2023-01-20 2024-08-03        M    <NA> 1964-10-19      58
   pat_ageday pat_sex  pat_bwt pat_memcat_parent pat_memcat_child is_covid
        <num>  <char>    <num>            <char>           <char>   <lgcl>
1:         NA       F       NA                 I                5    FALSE
2:         15       M 2.880697                 I                5       NA
3:         NA       M       NA                 I                4     TRUE
4:         NA       F       NA                 I                5       NA
5:         NA       M       NA                 D                1     TRUE
6:         NA       M       NA                 I                5       NA
   claim_status claim_payout claim_charge clin_discharge clin_outpatient
         <char>        <num>        <num>          <int>          <lgcl>
1:            G         9210      9210.00              1           FALSE
2:            G         2750      3004.58              1           FALSE
3:            D            0      2800.00              1            TRUE
4:            G         5000      6971.80              1           FALSE
5:            G         2450      2450.00              1            TRUE
6:            G        10400     15932.50              1            TRUE
   clin_emergency clin_acc clin_c1     c1 clin_c2     c2 clin_sdx clin_proc
           <lgcl>   <char>  <char> <list>  <char> <list>   <list>    <list>
1:          FALSE        W   NSD01  NSD01   O71.9     NA     O809
2:          FALSE        W   99460  99460    <NA>     NA
3:          FALSE        W   C19T2     NA    <NA>     NA
4:          FALSE        W   NSD01  NSD01    <NA>     NA
5:          FALSE        P   C19X1     NA    <NA>     NA
6:          FALSE        P   90935  90935    <NA>     NA     N030      3995
   clin_rvs clin_pdx clin_pdx_source
     <list>   <char>           <num>
1:    NSD01     O719               2
2:    99460     Z380               3
3:    C19T2      C19               1
4:    NSD01     O800               3
5:    C19X1      C19               1
6:    90935     N185               6

In [132]:
# Convert both id_hci and PMCC_NO to characters to ensure consistency for joining
result[, id_hci := as.character(id_hci)]
hci[, PMCC_NO := as.character(PMCC_NO)]

# Remove leading zeros from numeric PMCC_NO values, while preserving non-numeric values
hci[, PMCC_NO_stripped := fifelse(
  grepl("^[0-9]+$", PMCC_NO),
  sub("^0+", "", PMCC_NO), # Remove leading zeros from numeric strings
  PMCC_NO # Keep non-numeric values unchanged
)]

# Keep only necessary columns from hci for the join
hci_subset <- hci[, .(PMCC_NO_stripped, SOC_SECTOR, INST_NAME, CAT_24, REGION_NAME, PROVINCE_NAME)]

# Perform a left join, keeping all rows in result and only matching rows from hci
result <- merge(
  result,
  hci_subset,
  by.x = "id_hci",
  by.y = "PMCC_NO_stripped",
  all.x = TRUE, # Keep all rows from result
  all.y = FALSE # Only include matching rows from hci
)

# ----- Filter rows by allowed CAT_24 categories -----
allowed_categories <- c("INFIRMARY/DISPENSARY", "LEVEL 1 HOSPITAL", "LEVEL 2 HOSPITAL", "LEVEL 3 HOSPITAL")

# Count rows where CAT_24 is not in allowed categories
count_excluded <- result[!(CAT_24 %in% allowed_categories), .N]
cat("Number of rows where CAT_24 is not in the allowed categories:", count_excluded, "\n")

# Print rows to be excluded
if (to_debug) cat("Rows to be dropped due to invalid CAT_24:\n")
if (to_debug) print(result[!(CAT_24 %in% allowed_categories)])

# Drop rows where CAT_24 is not in the allowed categories
result <- result[CAT_24 %in% allowed_categories]
if (to_debug) str(result)
# ----- Filter rows where clin_outpatient is TRUE -----
# Count rows where clin_outpatient is TRUE
count_clin_outpatient_true <- result[clin_outpatient == TRUE, .N]
cat("Number of rows where clin_outpatient is TRUE:", count_clin_outpatient_true, "\n")

# Print rows to be excluded
if (to_debug) cat("Rows to be dropped due to clin_outpatient being TRUE:\n")
if (to_debug) print(result[clin_outpatient == TRUE])

# Drop rows where clin_outpatient is TRUE
result <- result[clin_outpatient != TRUE]
if (to_debug) str(result)
# ----- Filter rows where claim_status is not "G" -----
# Count rows where claim_status is not "G"
count_claim_status_not_G <- result[claim_status != "G", .N]
cat("Number of rows where claim_status is not 'G':", count_claim_status_not_G, "\n")

# Print rows to be excluded
if (to_debug) cat("Rows to be dropped due to claim_status not being 'G':\n")
if (to_debug) print(result[claim_status != "G"])

# Drop rows where claim_status is not "G"
result <- result[claim_status == "G"]
if (to_debug) str(result)
# Convert 'c1' from a list of character vectors into a single concatenated string
result[, c1_spc := sapply(c1, function(x) {
  if (is.null(x) || all(is.na(x))) {
    return(NA_character_) # Return NA if the list is empty or all values are NA
  } else {
    return(paste(sort(unique(x)), collapse = ",")) # Sort, remove duplicates, and concatenate
  }
})]

# ----- Handle duplicate rows based on specific columns -----
duplicate_columns <- c("id_pin", "pat_type", "pat_age", "pat_sex", "date_adm", "date_dis", "c1_spc", "claim_payout")

# Count duplicate rows based on the specified columns
count_duplicates <- result[duplicated(result[, ..duplicate_columns]), .N]
cat("Number of duplicated rows based on specified columns:", count_duplicates, "\n")

# Print duplicate rows
if (to_debug) cat("Rows with duplicated combinations of the specified columns:\n")
if (to_debug) print(result[duplicated(result[, ..duplicate_columns])])

# Drop duplicate rows, keeping only the first occurrence
result <- result[!duplicated(result[, ..duplicate_columns])]
if (to_debug) str(result)
# ----- Remove unnecessary columns and reorder remaining columns -----
# Remove unnecessary columns
result[, c("c1", "c1_spc", "c2", "clin_rvs") := NULL]

# Perform garbage collection to free up memory
gc()

# Set the column order to a specified structure
setcolorder(result, c(
  "id_year", "id_series", "id_pin", "id_hci", "id_hcp", "date_adm", "time_adm", "date_dis", "time_dis",
  "date_rec", "date_ref", "date_check", "date_ext", "pat_type", "pat_rel", "pat_bdate", "pat_age",
  "pat_ageday", "pat_sex", "pat_bwt", "pat_memcat_parent", "pat_memcat_child", "is_covid", "claim_status", "claim_payout",
  "claim_charge", "clin_discharge", "clin_outpatient", "clin_emergency", "clin_acc", "clin_c1", "clin_c2",
  "clin_sdx", "clin_proc", "clin_pdx", "clin_pdx_source", "SOC_SECTOR", "CAT_24", "INST_NAME", "REGION_NAME", "PROVINCE_NAME"
))

Number of rows where CAT_24 is not in the allowed categories: 5128
Number of rows where clin_outpatient is TRUE: 7631
Number of rows where claim_status is not 'G': 344

Number of duplicated rows based on specified columns: 0

       used    (Mb)  gc trigger (Mb)  max used (Mb)
Ncells 2828798 151.1  5040384   269.2  5040384 269.2
Vcells 7145761  54.6 21596529   164.8 21579085 164.7

In [133]:
# str(result)

In [134]:
saveRDS(result, here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, "stata", ".rds")), compress = TRUE)

Check if any of our identifiers are in exponential form e.g. "1.9e+07"

In [135]:
# str(result_after_cleaning)
print(result[grepl("e", id_series)])
print(result[grepl("e", id_pin)])
print(result[grepl("e", id_hci)])

Key: <id_hci>
Empty data.table (0 rows and 41 cols): id_year,id_series,id_pin,id_hci,id_hcp,date_adm...
Key: <id_hci>
Empty data.table (0 rows and 41 cols): id_year,id_series,id_pin,id_hci,id_hcp,date_adm...
Key: <id_hci>
Empty data.table (0 rows and 41 cols): id_year,id_series,id_pin,id_hci,id_hcp,date_adm...

In [136]:
# str(result)
# fwrite(result, "test.csv")
# Search for rows where any element in clin_sdx is "A"
result[, if (any(sapply(clin_sdx, function(row) "A" %in% row))) print(.SD), by = 1:nrow(result)]

     nrow

In [137]:
result <- readRDS(here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, "final", ".rds")))

In [138]:
# date_cols <- c("date_adm", "date_dis", "date_rec", "date_ref", "date_check", "pat_bdate", "date_ext")

# # Function to convert and replace dates before 1900-01-01 with NA
# convert_and_filter_dates <- function(x) {
#   # Replace dates before 1900-01-01 with NA
#   x[x < as.Date("1900-01-01")] <- NA_Date_
#   return(x)
# }

# if (is_unix) {
#   result[, (date_cols) := mclapply(.SD, convert_and_filter_dates, mc.cores = parallel::detectCores()), .SDcols = date_cols]
# } else {
#   result[, (date_cols) := lapply(.SD, convert_and_filter_dates), .SDcols = date_cols]
# }

In [139]:
date_cols <- c("date_adm", "date_dis", "date_rec", "date_ref", "date_check", "pat_bdate", "date_ext")

# Find rows where any date column has a date before 1900-01-01
rows_with_old_dates <- result[Reduce(`|`, lapply(.SD, function(x) x < as.Date("1900-01-01"))), .SDcols = date_cols]

# Print the resulting rows
print(rows_with_old_dates)

Null data.table (0 rows and 0 cols)

In [140]:
# print(head(result, 100))
# Print unique values of the 'clin_discharge' column
# print(unique(result$clin_discharge))

Export to Stata

In [141]:
result <- readRDS(here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, "stata", ".rds")))


# Define a function to convert list columns to character columns
convert_list_to_character <- function(dt) {
  # Loop through all columns in the data.table
  for (col in names(dt)) {
    if (is.list(dt[[col]])) {
      dt[, (col) := sapply(dt[[col]], function(x) {
        if (is.null(x) || all(is.na(x))) {
          return(NA_character_) # Return NA if the list is empty or all values are NA
        } else {
          return(paste(sort(x), collapse = ",")) # Sort and concatenate
        }
      })]
    }
  }
}

# Apply the conversion function to your data.table 'result'
convert_list_to_character(result)

# Export to Stata (.dta) format
write_dta(as.data.frame(result), here(checkpoint_10_path, paste0(checkpoint_10_prefix, year_to_load, suffix, ".dta")))

gcs_auth(email = gcs_email)
gcs_upload(
  file = here(checkpoint_10_path, paste0(checkpoint_10_prefix, year_to_load, suffix, ".dta")),
  bucket = gcs_bucket,
  name = paste0(gcs_spc_fpath, "/", paste0(checkpoint_10_prefix, year_to_load, suffix, ".dta")),
  predefinedAcl = "bucketLevel"
)

ℹ 2024-10-15 09:12:59.405274 > File size detected as  3.9 Mb

==Google Cloud Storage Object==
Name:                spc/stata2022_sampled_1361_.dta
Type:                application/octet-stream
Size:                3.9 Mb
Media URL:           https://www.googleapis.com/download/storage/v1/b/phic-claims-checkpoints/o/spc%2Fstata2022_sampled_1361_.dta?generation=1728983579566621&alt=media
Download URL:        https://storage.cloud.google.com/phic-claims-checkpoints/spc%2Fstata2022_sampled_1361_.dta
Public Download URL: https://storage.googleapis.com/phic-claims-checkpoints/spc%2Fstata2022_sampled_1361_.dta
Bucket:              phic-claims-checkpoints
ID:                  phic-claims-checkpoints/spc/stata2022_sampled_1361_.dta/1728983579566621
MD5 Hash:            wz+MmeEqrtBzA9dHHFb6PQ==
Class:               STANDARD
Created:             2024-10-15 09:12:59
Updated:             2024-10-15 09:12:59
Generation:          1728983579566621
Meta Generation:     1
eTag:                CJ3E1OCFkIkDEAE=
crc32c:              PPk+wg==

### Push to BQ

Push results to BQ if appropriate (i.e. if allowed by parameters)

In [142]:
result <- readRDS(here(checkpoint_2_path, paste0(checkpoint_2_prefix, year_to_load, suffix, "final", ".rds")))
result[, c("c1", "c2", "clin_rvs") := NULL]
# cat(unique(result$id_series), sep = "\n")

In [143]:
# test <- fread("/home/resurreccion_cmc_gmail_com/drg-pipeline/data-cleaning/data/claims/raw/claims_extract_CLAIMS 2022.tsv", colClasses = "character", nrows = 100)

# print(head(test, 100))

In [144]:
if (nrow(result) == total_rows) bq_table <- paste0("claims_", year_to_load, "1231")

# Check if the table should be dropped and replaced
if (to_drop_bq) {
  tryCatch(
    {
      bq_table_delete(bq_table(gcp_proj, bq_dataset, bq_table))
      message("Table dropped successfully.\n")
    },
    error = function(e) {
      # If the table does not exist, just continue
      if (grepl("Not found", e, ignore.case = TRUE)) {
        message("Table does not exist, nothing to drop.\n")
      } else {
        # If it's a different error, re-throw the error
        stop(e)
      }
    }
  )
}

# Attempt to create the table
tryCatch(
  {
    bq_table_create(
      bq_table(gcp_proj, bq_dataset, bq_table),
      fields = fromJSON(here("data-cleaning/r_scripts", "bq_schema_cleaning.json"), simplifyDataFrame = FALSE)
    )
    skip_bq_upload <<- FALSE
    message("Table created successfully.\n")
  },
  error = function(e) {
    # Check if the error message indicates that the table already exists
    if (grepl("already exists", e, ignore.case = TRUE)) {
      skip_bq_upload <<- TRUE
      message("Table already exists. Skipping creation and upload.")
    } else {
      # If it's a different error, re-throw the error
      stop(e)
    }
  }
)

# Upload to BQ only if table is empty
if (to_bq && !skip_bq_upload) {
  # tryCatch(
  #   {
  #     bq_table_upload(
  #       bq_table(gcp_proj, bq_dataset, bq_table),
  #       values = result,
  #       write_disposition = "WRITE_EMPTY"
  #     )
  #     message("Data uploaded successfully with WRITE_EMPTY.\n")
  #   },
  #   error = function(e) {
  #     if (grepl("already exists", e, ignore.case = TRUE)) {
  #       # Handle the specific "already exists" error
  #       message("Upload skipped: table already exists and is not empty.")
  #     } else {
  #       # Handle all other errors
  #       message("Error during upload: ", e)
  #     }
  #   }
  # )
  chunk_size <- 1000000 # Adjust the chunk size based on memory availability
  num_chunks <- ceiling(nrow(result) / chunk_size)

  for (i in seq_len(num_chunks)) {
    chunk <- result[((i - 1) * chunk_size + 1):min(i * chunk_size, nrow(result)), ]

    bq_table_upload(
      bq_table(gcp_proj, bq_dataset, bq_table),
      values = chunk,
      write_disposition = if (i == 1) "WRITE_EMPTY" else "WRITE_APPEND"
    )
  }
  # gcs_auth(email = gcs_email)
  # gcs_upload(
  #   file = here(checkpoint_4_path, paste0(checkpoint_4_prefix, year_to_load, suffix, ".txt")),
  #   bucket = gcs_bucket,
  #   name = paste0(gcs_pre_fpath, "/", paste0(checkpoint_4_prefix, year_to_load, suffix, ".txt")),
  #   predefinedAcl = "bucketLevel"
  # )
}

Table dropped successfully.

Table created successfully.

In [145]:
# str(result)

## Runtime Estimation

In [146]:
# Print time estimates along with estimate for full claims file
print_time_estimates()

Time spent (total)               : 69.691 sec elapsed
Time spent (t/row) for 20.4k rows: 3.41 msec
Time (est) (total) for 12.8m rows: 725.95 min

## Debugging

In [147]:
# in case we want to run this cell independently:
source(here::here("data-cleaning/r_scripts", "03_timing-debug-functions.R"))

# Consolidate all r_scripts scripts into debug.R; useful for debugging
concatenate_r_files(
  here::here("data-cleaning/r_scripts"),
  here::here("data-cleaning/debug/debug.R")
)

if (.Platform$OS.type == "unix") system("cd ~/drg-pipeline && jupyter nbconvert --no-prompt --to script data-cleaning/drg-cleaning.ipynb --output debug/drg-cleaning")

## Cleanup

In [148]:
if (FALSE) {
  to_flush_master <- to_debug <- TRUE
  to_flush_partial <- FALSE
}

# Define the paths and corresponding conditions
paths <- list(
  to_flush_master = c(
    "data-cleaning/cache",
    "data-cleaning/data/profvis",
    "data-cleaning/data/aux-files",
    "data-cleaning/data/checkpoints",
    "data-cleaning/debug"
  ),
  to_flush_partial = c(
    "data-cleaning/data/claims/raw/parts",
    "data-cleaning/data/claims/raw/samples"
  )
)

# Iterate over the paths and conditions to delete them if the condition is true
for (condition in names(paths)) {
  if (get(condition)) {
    system(paste(
      "rm -r",
      paste(here::here(unlist(paths[[condition]])), collapse = " ")
    ))
  }
}

if (to_debug) {
  rm(list = ls())
  gc()
}